Variables {FE}
Terminals {cabdfe}
Equation: aacfcbebeabbeecFbfceaccdeaeddbeefacddaa = aacfcbebeabbeecbbbEdaa
Equation: ecffdbaddfbbbffaafFeddfebaadaacafeabcae = ecffdbaddfbbbffaafbbeddfebaadaacafeabcae
Equation: fdbcacfaFdfcddbefafedefcffeebfecdecdbfd = fdbcacfaFdfcddbefafedefcffeebfecdecdbfd
SatGlucose(100)