(set-logic QF_S)
(declare-fun E () String)
(declare-fun J () String)
(assert (= (str.++  "ebdbbbfd" E "cacebbeebbeeeefcdee")  (str.++  "ebdbbbfdadebeceaad" J "cebbeebbeeeefcdee") ))
(assert (= (str.++  "ceffeeebcafbbfbeefabfeeeeaddddeb" J "dfe")  (str.++  "ceffeeebcafbbfbeefabfeeeeaddddeb" J "dfe") ))
(assert (= (str.++  "f" J "dacbfabdafacfddecbaffeaeeffedacacc")  (str.++  "fbbecadacbfabdafacfddecbaffeaeeffedacacc" "") ))
(assert (>=(* (str.len J) 9) 18))
(check-sat)
(get-model)
