(set-logic QF_S)
(declare-fun G () String)
(declare-fun C () String)
(declare-fun D () String)
(assert (= (str.++  "eddda" D "bcbaa")  (str.++  "edddaddfbabeafd" C "fadeacdcaeaccbabcbaa") ))
(assert (= (str.++  "fdedacfdaddabddfebacdcccfa" G "dbcdeeecce")  (str.++  "fdedacfdaddabddfebacdcccfa" G "dbcdeeecce") ))
(assert (= (str.++  "adaadecdcceaceeecebfcbcdffefbabccf" G "cc")  (str.++  "adaadecdcceaceeecebfcbcdffefbabccfafddcc" "") ))
(assert (<=(* (str.len C) 12) 576))
(check-sat)
(get-model)
