(set-logic QF_S)
(declare-fun I () String)
(declare-fun J () String)
(assert (= (str.++  "cdc" J J "d" J "cf" J "c" J "fa" I "fcddbdbbdddcff")  (str.++  "cdc" J J "d" J "cfac" J "f" J I "fcddbdbbdddcff") ))
(assert (= (str.++  J "edaed" J J "fcdedbeeddbcdcfddaeedfcdecceedcd")  (str.++  "aed" J "eda" J "fcdedbeeddbcdcfdd" J "eedfcdecceedcd") ))
(assert (= (str.++  "fbafe" J "cdccbcbbcaeaffecdabdd" J "deb" J "fecffdee")  (str.++  "fbafeacdccbcbbc" J "e" J "ffecdabddadebafecffdee") ))
(assert (<=(* (str.len J) 7) 14))
(check-sat)
(get-model)
