Variables {IEA}
Terminals {cabdfe}
Equation: aebcdaecfbcdcbAIAdaefccAfaaedfdd = aE
Equation: cccbedeAedAeacbfcAdadeedaAcfaeaaccfcaAdA = cccbedebedbeacAfcbdadeedaAcfaeaaccfcabdb
Equation: bfffffecAadfdeaAebbcebeAcaccceaecafeefAc = bfffffecbadfdeabeAAceAeAcaccceaecafeefbc
SatGlucose(100)