(set-logic QF_S)
(declare-fun I () String)
(declare-fun E () String)
(declare-fun A () String)
(assert (= (str.++  "aebcdaecfbcdcb" A I A "daefcc" A "faaedfdd")  (str.++  "a" E) ))
(assert (= (str.++  "cccbede" A "ed" A "eacbfc" A "dadeeda" A "cfaeaaccfca" A "d" A)  (str.++  "cccbedebedbeac" A "fcbdadeeda" A "cfaeaaccfcabdb") ))
(assert (= (str.++  "bfffffec" A "adfdea" A "ebbcebe" A "caccceaecafeef" A "c")  (str.++  "bfffffecbadfdeabe" A A "ce" A "e" A "caccceaecafeefbc") ))
(check-sat)
(get-model)
