(set-logic QF_S)
(declare-fun H () String)
(declare-fun C () String)
(declare-fun G () String)
(assert (= (str.++  "cbaafdfbb" H "cd")  (str.++  "cb" C "facaf" G "dbeabdecccfbcbcd") ))
(assert (= (str.++  "bbeeceaadcaeaebbbcbfddefccbad" G "fafbcca")  (str.++  "bbeeceaadcaeaebbbcbfddefccbad" G "fafbcca") ))
(assert (= (str.++  "edfefbcedfefdceda" G "afaadbeebaefcdebbeb")  (str.++  "edfefbcedfefdceda" G "afaadbeebaefcdebbeb") ))
(check-sat)
(get-model)
