(set-logic QF_S)
(declare-fun D () String)
(declare-fun A () String)
(assert (= (str.++  "cdebed" D "ccceebddbbadb" D "deebadabaaacdebcce")  (str.++  "cdebedebdccc" A "ce") ))
(check-sat)
(get-model)
