(set-logic ALL)
(declare-fun B () String)
(declare-fun F () String)
(declare-fun E () String)
(assert (= (str.++  "efbghbcgghaidgbajjigfjbaffeidgjiajeaigigcbaicejjchh" E "ihghgdbgihegecaidjefhcijdgdbhh")  (str.++  "efbghbcgg" B "ajeai" F "jefhcijdgdbhh") ))
(check-sat)
