(set-logic QF_S)
(declare-fun D () String)
(declare-fun A () String)
(assert (= (str.++  "acab" A "bccbccabacbcccbabbbbaaccaccbacbcacabcbaaabcabacacaaccbcccacaaabaaa")  (str.++  "acabccbacbbbbbcbbcccbbaacabb" D "ccaccbacbcacabcbaaabcabacacaaccbcccacaaabaaa") ))
(check-sat)
(get-model)
