Variables {A}
Terminals {cgabhdfei}
Equation: ghaiehabecigefgibdchcidcbhchagdgchiacdchcghfcaafbfgaghcgedddaaghchgdhgghibegagghaiciacdgbcadhbcgfifefgcbfcagddebddbeibedfecbh = ghaiehabecigefgibdchcidcbhchagdgAbddbeibedfecbh
SatGlucose(100)