Variables {HEJ}
Terminals {dcgfeab}
Equation: ccdegdegecdfbbfdgeedcaHafacbdfaeegdbaJeaacaEgefffccecfddcddcbgffcdaagebfeafddedegcdfe = ccdegdegecdfbbfdgeedcafacafacbdfaeegdbaJeaacaEgefffccecfddcddcbgffcdaagebfeafddedegcdfe
SatGlucose(100)