Variables {CA}
Terminals {dcfeab}
Equation: aaadbcbAccdcccdebbcffcbbadAfafcbccbAedfaAccaacffaaAfeafacdccadabbdbAeccbcbcdedecaaddaebfddbaabcabffadcaeAaababfaeed = aaadbcbfccdcccdebbcAAcbbadAfaAcbccCdabbdbAeccbcbcdedecaaddaebAddbaabcabAAadcaefaababfaeed
SatGlucose(100)