(set-logic QF_S)
(declare-fun H () String)
(declare-fun D () String)
(declare-fun F () String)
(assert (= (str.++  "bcc" H "cagdjdaeb" D "icicaccdeadfeacehdc")  (str.++  "bccecijbbifhciibcfaaebecagdjdaeb" F "jaachbbbcbiicicaccdeadfeacehdc") ))
(check-sat)
(get-model)
