(set-logic QF_S)
(declare-fun N () String)
(declare-fun O () String)
(declare-fun E () String)
(assert (= (str.++  E "bbbdbcdddbbdbdabaccdddbcbccdbd" "")  (str.++  "cabbcac" N "cdaddbbacb" O "dddbcbccdbd") ))
(check-sat)
(get-model)
