Variables {CA}
Terminals {dcgfeab}
Equation: fdfafeafegAcbgcdbgbfbgfeacegbcddgagbebgeadbbacdfaefaeffffbfgagaggebbcccddacecaddfed = fdfafeafegbbfbgegffgedegdfcgebgecgccadgdaefbfCdbbacdfaefaeffffbfgagaggebbcccddacecaddfed
SatGlucose(100)