(set-logic QF_S)
(declare-fun C () String)
(declare-fun F () String)
(assert (= (str.++  "bcabbbcbccbcccccca" C "cbaabccabbcaccbaaaaba")  (str.++  "bcab" F "cbcccccca" C "cbaabccabbcaccbaaaaba") ))
(check-sat)
(get-model)
