(set-logic QF_S)
(declare-fun M () String)
(declare-fun B () String)
(declare-fun E () String)
(assert (= (str.++  "c" B "bdeb" E "cbacbabadd")  (str.++  "ceeecbcbbcebdebbbbee" M "bacbabadd") ))
(check-sat)
(get-model)
