(set-logic QF_S)
(declare-fun B () String)
(declare-fun A () String)
(assert (= (str.++  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" B B "aaaaaaaa")  (str.++  A B "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") ))
(check-sat)
(get-model)
