(set-logic QF_S)
(declare-fun B () String)
(declare-fun G () String)
(assert (= (str.++  "fbcadfffcabbcefaccaddaeefbdadfedebebcadc" B "debdfcdaabaaadbfab")  (str.++  "fbcadfffcabbcefaccaddaeefbdadfed" G "cbeafceaaefdaeefedebdfcdaabaaadbfab") ))
(check-sat)
(get-model)
