Variables {A}
Terminals {dcgfeab}
Equation: gcfedcedggeedcfedgfcgbabgcgAgacaedgdeaeddafdcdefgbafdabfeaddbgfeddefadaeddcdaegbbbccdbffdfbefbdgcdbfggfcdffgfcabebdgabdg = gcfedcedggeedcfedgfcgbabgcgdccffccddcffgacaedgdeaeddafdcdefgbafdabfeaddbgfeddefadaeddcdaegbbbccdbffdfbefbdgcdbfggfcdffgfcabebdgabdg
SatGlucose(100)