Variables {A}
Terminals {cgabhdfei}
Equation: fbaiigcfaggfiehhgbacfbccafcbaebecbhfbdidaedhbgfcddfcbAfhgbfcfcccgfdafeehaibhficaedfficcdgae = fbaiigcfaggfiehhgbacfbccafcbaebecbhfbdidaedhbgfcddfcbcffbcdabhgahehfdecfaffdedafgicdacdcgebecagchdccgfacadbahgiagfhgbfcfcccgfdafeehaibhficaedfficcdgae
SatGlucose(100)