Variables {BFA}
Terminals {dcgfeab}
Equation: deecbcgcfgbebdccagageBegbAfdddbaabfegbbggcadfaaeagdf = deecbcgcfgbebdccagageBegbebcaeccedbedefbfdFgbagebcbfacgadbefcffcgceeeddfdddbaabfegbbggcadfaaeagdf
SatGlucose(100)