(set-logic ALL)
(declare-fun B () String)
(declare-fun F () String)
(assert (= (str.++  "adaebhihggahhgdfdifh" B "hdfhcdibhihegaciggice")  (str.++  "adaebhihggahhgdfdifhehbfbddbhcfahehcfggcegabdddcgacdfge" F "gaciggice") ))
(check-sat)
(get-model)
