Variables {BC}
Terminals {dcgfeab}
Equation: fabeafbgdaggecacdcadgfbgegfdfeebcggecaaebcefabgaaecdbddcfdBfccabggdaedcafgcbadaagdaaebc = fabeafbgdaggecacdcadgfbgegfdfeebcggecaaebcefabCecfdecdcfaagfaeeaccbafccabggdaedcafgcbadaagdaaebc
SatGlucose(100)