Variables {BDC}
Terminals {cgabhdjfei}
Equation: eafBjgfaihdfcbgffCgebgjgfdebeajefbe = eafbgieagfdcahedjjjdcjgfaihdfcbgffbafedhbebghehgfehibbjdejbdafiidcbbecDiahceaggigheiebjecfgebgjgfdebeajefbe
SatGlucose(100)