Variables {DA}
Terminals {ab}
Equation: bDbbbabbabbaabababababbabaabbbbaaDDbabbbbbaDDAbbabababbbaabaababaaaaabDbbbababbDababaaaaaabbbabbaabbab = baabbbbabbabbDababababbabaabbbbaaaabaabbabbbbbaDaabbbbbbababaabaababbaDbbDbbbDbabababbbDDabaaaaabaabbbbababbaabababaaaaaabbbabbDbab
SatGlucose(100)