Variables {B}
Terminals {cgabhdjfei}
Equation: hbgdjgabehbcihfhggfdijbjcBgiedhcjcibfffacgbgejibbgjadjeddhjehjj = hbgdjgabehbcihfhggfdijbjchjjfbfeijebfjabciadjchegiiedjdiihifdbfebiechbegiedhcjcibfffacgbgejibbgjadjeddhjehjj
SatGlucose(100)