Variables {GEJ}
Terminals {acb}
Equation: caaacJbababcbabaaccaabbabaaacabcababcaaaabaaccEcccabbbabccacabccaacbbabcbbcbacbccbccbaaacba = caaacJbababcbabaaccaabbabaaaGcbbcbacbccbccbaaacba
SatGlucose(100)