Variables {IBEJ}
Terminals {dcgfeab}
Equation: dcbgbggeagdfbbgdfebffacgEgcedacebdfabcbfafgacggebbfegfdceeabecgdgbcd = dcbgbggeagdfJbBfbffgbegacfdbdIbdfabcbfafgacggebbfegfdceeabecgdgbcd
SatGlucose(100)