Variables {LCH}
Terminals {dcgfeab}
Equation: fgdgbgeaafLfabfafbefgbdcaffcaagbccbHagdbfabbcceccgcecefeadeagddgeebdedbcfgabgeagfggdebecccecfcgf = fgdgbgeaafbfeeedefeCabbcceccgcecefeadeagddgeebdedbcfgabgeagfggdebecccecfcgf
SatGlucose(100)