Variables {CA}
Terminals {cgabhdfe}
Equation: cebhhefgdhhfdbdhcghaadfhagcgceeffahfeeaecgeaafgebecchabcaaecefgAdecbaadbaghchcfcgdbhchfbcfehbefgehgfadhdfhebfebdfhce = cebhhefgdhhfdbdhcghaadfhagcgceeffahfeeaecgeaafgebecchabcaCbfebdfhce
SatGlucose(100)