(set-logic ALL)
(declare-fun C () String)
(declare-fun E () String)
(assert (= (str.++  "ccbccafdefdbfbcecefefbbbfef" C "deb" E "cbdfcbedcafaebbcdebdafdcbbedbbaeaadcaccbebcfffdccbfbabfcafe")  (str.++  "ccbccafdefdbfbcecefefbbbfef" C "debcbfbdefcbdfcbedcafaebbcdebdafdcbbedbbaeaadcaccbebcfffdccbfbabfcafe") ))
(check-sat)
(get-model)
