Variables {KBG}
Terminals {dcgfeab}
Equation: defcfacdggfKcfbeddecfcgegddagccbbbeebcdegadcddbcbcfbadeeadafcBbbfgebdbeeabdaaabffageddg = defcfacdggfcddcfGaccfafcdgdefffacfecdfedbagacfgefgeabbfgebdbeeabdaaabffageddg
SatGlucose(100)