(set-logic QF_S)
(declare-fun I () String)
(declare-fun G () String)
(declare-fun E () String)
(declare-fun F () String)
(assert (= (str.++  E E E G)  (str.++  F F I "aaaaaaaaa" G G "aaaaaaaaaa" G "aaaaaaaa") ))
(check-sat)
(get-model)
