Variables {CA}
Terminals {cgabhdfei}
Equation: dgabddihghgafhhdhiigiffddgbgcbihhfaiccbicchihaddbfficdbdhdbibifceaceifbifadcfeacdfhefhacehiicbgiedhhcbhbicfdbiehfgaadhcahecicbchcdbabfiidfbdf = dgabddihghgafhhdhiigiffdChhfaicAacehiicbgiedhhcbhbicfdbiehfgaadhcahecicbchcdbabfiidfbdf
SatGlucose(100)