Variables {FE}
Terminals {cgabhdjfei}
Equation: aijebibadgbbbgebhfjaieeagjfeeceibFghjEeddhiffcgbdibgheacdijbgighgaiibhgachdjj = aijebibadgbbbgebhfjaieeagjfeeceibcffjjfdbciciaefighjEeddhiffcgbdibgheacdijbgighgaiibhgachdjj
SatGlucose(100)