Variables {CF}
Terminals {ab}
Equation: bbbaaabbaaaaaaabCabbbabbaababbababaaabbbbbbbbaabbbbaabbabbaabbabaaabbbbbaababaaaba = bbbaaabbaaaaaaabaabaabbaabFbbababaaabbbbbbbbaabbbbaabbabbaabbabaaabbbbbaababaaaba
SatGlucose(100)