Variables {MBAJ}
Terminals {cgabhdfei}
Equation: cfaeggdifAiigbacihegbhifichcbJahBcfbcfideggigdfigciibeefhigcegaeiaefihgdffbaicfiehfhai = cfaeggdifefhahcciigbacihegbhifichMfdhicfbcfideggigdfigciibeefhigcegaeiaefihgdffbaicfiehfhai
SatGlucose(100)