(set-logic QF_S)
(declare-fun H () String)
(declare-fun B () String)
(declare-fun F () String)
(declare-fun E () String)
(declare-fun A () String)
(assert (= (str.++  B "abbabbadeead" A "acbaca" H "aeb" H "edb" A "c" A "c" H "ebabcc" E "cbc" H H)  (str.++  A "bb" H "abb" A "bba" H "e" F "cad" E "bde" H "b" A "cacdebabcc" A "ecbcd" H) ))
(check-sat)
(get-model)
