(set-logic ALL)
(declare-fun A () String)
(assert (= (str.++  "fbaiigcfaggfiehhgbacfbccafcbaebecbhfbdidaedhbgfcddfcb" A "fhgbfcfcccgfdafeehaibhficaedfficcdgae")  (str.++  "fbaiigcfaggfiehhgbacfbccafcbaebecbhfbdidaedhbgfcddfcbcffbcdabhgahehfdecfaffdedafgicdacdcgebecagchdccgfacadbahgiagfhgbfcfcccgfdafeehaibhficaedfficcdgae" "") ))
(check-sat)
(get-model)
