(set-logic QF_S)
(declare-fun N () String)
(declare-fun M () String)
(declare-fun G () String)
(assert (= (str.++  "dcdceb" N)  (str.++  "dcdceb" M "cb" M "ae" G "deecaebedea") ))
(check-sat)
(get-model)
