(set-logic QF_S)
(declare-fun F () String)
(declare-fun E () String)
(assert (= (str.++  F "hbaahhegb" F E "cbaaedcgdfgede" F "gbegebf")  (str.++  "fhbaahhegb" F "cb" F "hhcb" F "c" F F "eedhhecbaaedcgd" F "gedefgbegebf") ))
(check-sat)
(get-model)
