Variables {A}
Terminals {dceab}
Equation: cdacdeceecacedddeaedaebdcababaedbbddeeceaecccbdeecbdcecbaedbacacdebecedcabccdabccabbddbcbbacebcbbabcbdabaadebecabaccbaaceaecaabebcada = cdacdeceecacedddeaedaebdcababaedbbddeeceaecccbdeecbdAcdabccabbddbcbbacebcbbabcbdabaadebecabaccbaaceaecaabebcada
SatGlucose(100)