(set-logic QF_S)
(declare-fun D () String)
(declare-fun E () String)
(assert (= (str.++  "geiebjgig" E "ajfdjbgijciabdefeedcc")  (str.++  "geiebjgigiacbdjddcdcbibcaabejbghcegibigbceaaefghbdehhfcbbecjhfgigf" D "gijciabdefeedcc") ))
(check-sat)
(get-model)
