Variables {DE}
Terminals {dcgfeab}
Equation: dffddgcefafggbeafadafbcacfdfcdffbfcbeeaegbaegcdEfeecegffcfeaagfcadfcffdeddbgdbbgceeb = dffddgcefafggbeafadafbcacfdfcdffbfcbeeaegbaegcdbddcaddgfgadacdgfgbdbccDffcecbaefcfegebadbfagecfbdbfafeecegffcfeaagfcadfcffdeddbgdbbgceeb
SatGlucose(100)