Variables {A}
Terminals {dcgfeab}
Equation: feefdAgfeaceebadcefdbddfgdbgcAAddfcecbaabacgdadeceaeabfbbAfebeffadbffdgcfgbgdaedgccedcbdgaccbdfdefabadf = feefdeggfeaceebadcefdbddfgdbgcegAddfcecbaabacgdadeceaeabfbbegfebeffadbffdgcfgbgdaedgccedcbdgaccbdfdefabadf
SatGlucose(100)