(set-logic QF_S)
(declare-fun K () String)
(declare-fun J () String)
(declare-fun N () String)
(declare-fun M () String)
(declare-fun C () String)
(assert (= (str.++  "abfbdegbhh" N "c" C "b" K "begcabbg" M "eafgghca" C)  (str.++  "abfbdegbhh" N "cd" J "egcabbg" M "eafgghca" C) ))
(check-sat)
(get-model)
