(set-logic QF_S)
(declare-fun H () String)
(declare-fun E () String)
(declare-fun J () String)
(declare-fun O () String)
(declare-fun M () String)
(declare-fun D () String)
(assert (= (str.++  "ebf" E "jihfch" D "da" J "c" H J "c" D "jgc" D "aci" D "hhhh" J D "i" D "ajfefccghiahgdbjdd" D)  (str.++  O "jafijihfchjda" J "cahaecjjg" M "hh" J "ji" D "a" D "f" J "fccghiahgdbjdd" D) ))
(check-sat)
(get-model)
