Variables {DEA}
Terminals {dcgfeab}
Equation: ffAbAeagacdebfegegdbeaeggdaegeegebfcgbfgefeAedafbAdddfEbbbaaAdaaccabAdfedffeea = ffcbceagaAdebfegegdbeaeggdaegeegebfcgDAdddfEbbbaacdaaAcabAdfedffeea
SatGlucose(100)