(set-logic QF_S)
(declare-fun C () String)
(declare-fun A () String)
(assert (= (str.++  "gadfgfdabg" C "gcefaecbgddefbefcfbf")  (str.++  "gadfgfdabgaaacbdgcefbbgeegfdcdcdacfaddeegdegcccaedc" A "gddefbefcfbf") ))
(check-sat)
(get-model)
