Variables {BD}
Terminals {cgabhdfe}
Equation: bebedhdDfcadechdaddffaebfhdeBchdegeecbbacggbgcbefcfhbgabhcgecfgeehaeafaaaahchbegehchegbcegbcdhbcd = bebedhdDfcadechdaddffaebfhdegccchcbdcehedcehaeachghehhededaddhcehgbchdegeecbbacggbgcbefcfhbgabhcgecfgeehaeafaaaahchbegehchegbcegbcdhbcd
SatGlucose(100)