(set-logic QF_S)
(declare-fun K () String)
(declare-fun G () String)
(declare-fun E () String)
(declare-fun O () String)
(declare-fun C () String)
(assert (= (str.++  "b" C "bb" K E O O C C "baca" C O)  (str.++  "b" C "b" G "ba" E "abc") ))
(check-sat)
(get-model)
