Variables {DA}
Terminals {acb}
Equation: acabAbccbccabacbcccbabbbbaaccaccbacbcacabcbaaabcabacacaaccbcccacaaabaaa = acabccbacbbbbbcbbcccbbaacabbDccaccbacbcacabcbaaabcabacacaaccbcccacaaabaaa
SatGlucose(100)