Variables {HKEL}
Terminals {cgabhdfei}
Equation: ebcgadKdiecfaiifeeafffgafbhgdccdhfffdeffiebhieiefhHhhbehehbbgeghiggcdfbgadbgcdfcfdhhcfhfdcfcifefhggifheggbebfcca = ebcgLecfaiifeeafffgafbhEeggbebfcca
SatGlucose(100)