Variables {DBGC}
Terminals {cgabhdfei}
Equation: eccGgiafdaeCbdaebcdheefccbbadiihhiBgheghihfceciagbggeecedbhdfggeadccfdichdcecdfg = eccGgiaDhfgheghihfceciagbggeecedbhdfggeadccfdichdcecdfg
SatGlucose(100)