(set-logic QF_S)
(declare-fun F () String)
(declare-fun E () String)
(assert (= (str.++  "gdaafhhaebdagfaefcbdffbcfdcf" E "gddbbegcbgeaacfdb")  (str.++  "gdaafhhaebdagfaefcbdffbcfdcffee" F "aegbbdecahdfdefdcdbaahafegddbbegcbgeaacfdb") ))
(check-sat)
(get-model)
