(set-logic QF_S)
(declare-fun C () String)
(declare-fun A () String)
(assert (= (str.++  "cddabcbbdbbbaaabbdaaaabadadbabbddabd" A C "bacbdcb")  (str.++  "cddabcbbdbbbaaabbdaaaabadadbabbddabdcbd" C "ba" A "cb") ))
(check-sat)
(get-model)
