Variables {BFE}
Terminals {ab}
Equation: bbaaabbbabBbabbbbbabbbbbabbbabbBbbbaEaaabbBaaaaaBbbaabbbaabbbbbbbbaabababaa = bbaaabbbabbabBbbbbabbbbbabbBbbabbbbaaabbBbabaabaaaababbFaabbbabaaaaababbbaabbbaabbbbbbbbaabababaa
SatGlucose(100)