(set-logic QF_S)
(declare-fun B () String)
(declare-fun F () String)
(assert (= (str.++  "ccacbbcbcaa" B "bbcaa")  (str.++  "ccacbbcbcaabaaacbabcccbcbbbccab" F "ccbcbcbabbcaccbbaaccacacccaabcccaaaaaabcbbcaa") ))
(check-sat)
(get-model)
