(set-logic ALL)
(declare-fun I () String)
(declare-fun M () String)
(declare-fun E () String)
(assert (= (str.++  "gaeaii" E "cgcjagjeffgghaff")  (str.++  "ga" I "bjgfbeadhbehdifeijieadddjaidjhg" M "jjajjjhebcedeifhiaiejfdcdfcgcjagjeffgghaff") ))
(check-sat)
(get-model)
