Variables {A}
Terminals {dceab}
Equation: baeeaaaeebbbdcddcbdcbcbAbbddaacebccdaaedeccbdbeeedaacddedacdbcedbbabcdbbccb = baeeaaaeebbbdcddcbdcbcbcdccbebdabceecacceaeabbddaacebccdaaedeccbdbeeedaacddedacdbcedbbabcdbbccb
SatGlucose(100)