Variables {ME}
Terminals {dcgfeab}
Equation: bggfadfebcbcddebgbadgabffeegcbbgceaceaefefeababacedfcafdbEbgc = bggfadfebcbcddebgbadgabffeegcbbgcMafbeegcfafgbfbceadaeecaegfadgebbfdcddafcaeadaafdeabgeccceagaecdbgc
SatGlucose(100)