Variables {CE}
Terminals {dcfeab}
Equation: ccbccafdefdbfbcecefefbbbfefCdebEcbdfcbedcafaebbcdebdafdcbbedbbaeaadcaccbebcfffdccbfbabfcafe = ccbccafdefdbfbcecefefbbbfefCdebcbfbdefcbdfcbedcafaebbcdebdafdcbbedbbaeaadcaccbebcfffdccbfbabfcafe
SatGlucose(100)