Variables {DJ}
Terminals {acb}
Equation: bbaabbbacbJccbccccbabaacbabaabbaacbbacaaaaabcbabccccbccaabacbbccbcbaaD = bbaabbbacbbbbbcbcbcacbbabDaabaaabacDbbcbbcacccbbDaccabbaabccccDaccbccccbabaacbabaabbaacbbacaaaaabcbabccccbcDabacbbccbcbaaca
SatGlucose(100)