Variables {HGJ}
Terminals {cgabhdjfei}
Equation: debgjbaigeeijejgaJgiicHjegjjbeiidhebbgifjcgigejeddaiahageajjfiejajdajfbcjehgeec = debgjbaigeeijejgabfcgecjfaGfjcgigejeddaiahageajjfiejajdajfbcjehgeec
SatGlucose(100)