Variables {GEAD}
Terminals {dcfeab}
Equation: aadbabccceabfffdcbdaadffeGfdeccdddefededcdbeecfabcAfbcbEefcceeaadbadcfacddbffddcadeed = aadbabccceabfffdcbdaadffeGfdeccdddefededcdDdbffddcadeed
SatGlucose(100)