(set-logic QF_S)
(declare-fun C () String)
(declare-fun F () String)
(declare-fun E () String)
(declare-fun D () String)
(assert (= (str.++  "gfbhbefgbadbhebdddghdg" E "h" C "edcdcb")  (str.++  E "bhbefg" F D "acbdf" E "bchfcdegcecedcdcb") ))
(check-sat)
(get-model)
