(set-logic QF_S)
(declare-fun B () String)
(declare-fun D () String)
(declare-fun A () String)
(declare-fun C () String)
(assert (= (str.++  A "cc" A "bcc" B)  (str.++  C "cc" A "b" D "bc" C "c" A) ))
(check-sat)
(get-model)
