(set-logic ALL)
(declare-fun A () String)
(assert (= (str.++  "defefcbeebbbdcfeaeadabfaaeeaddddeaaefddfaffbdcfbaefbfadeb" "")  (str.++  "defefcbee" A "aaefddfaffbdcfbaefbfadeb") ))
(check-sat)
(get-model)
