(set-logic QF_S)
(declare-fun G () String)
(declare-fun B () String)
(declare-fun F () String)
(declare-fun E () String)
(assert (= (str.++  F "aaaaaa" B F "aaaaaa" E "aaaaa")  (str.++  B "aaaaaa" F F G "aaaaaaaaaaaaa") ))
(check-sat)
(get-model)
