(set-logic QF_S)
(declare-fun B () String)
(declare-fun A () String)
(declare-fun C () String)
(declare-fun D () String)
(assert (= (str.++  "fdfedebdfbeffbda" C "fddc")  (str.++  "fdfedebdfbeffbdacabfdf" B "dc") ))
(assert (= (str.++  "ea" A)  (str.++  "eacdbdbbdfbefddcfadf" B "f" D "cabacfffabddccbfdecbdaaadddbecbddabbaeeedaec") ))
(assert (= (str.++  "eedccdeabfbafafffbbabcbfccbba" A "feacbbfbefcebefcfcaacaeecbcbccacbdedeaccabfd")  (str.++  "eedccdeabfbafafffbbabcbfccbbafdfbdedd" B "fcfcaacaeecbcbccacbdedeaccabfd") ))
(assert (= (str.++  "cafccdaccdbccfaacbcabfdfaabdace" C "fecddcacbebaecbe")  (str.++  "cafccdaccdbccfaacbcab" B "dabcfebaafcdfeeddbefecddcacbebaecbe") ))
(assert (= (str.++  "badbdeddbdaddafafadeceaebf" A "cdbdacabacbefdddecebbfcdcfc")  (str.++  "badbdeddbdaddafafa" B "cbbdfafedfcdbdacabacbefdddecebbfcdcfc") ))
(assert (= (str.++  "ffe" A "f" C "ceecfaabaadebacefaddfbcbadbadacfdabccbbddeadf")  (str.++  "ffeffdfcbcefceeffdadf" B "ddeadf") ))
(assert (= (str.++  "eaaafbbcbafddfdbbd" A "faabddbbbdbbeedbadbdfee")  (str.++  "eaaafbbcbafddfdbbdaebeeece" D "eddadcffecffeaaeebafaabddbbbdbbeedbadbdfee") ))
(assert (= (str.++  "eedebeffcdeccd" B "fdabceffadfaeaaefeaaddadebfddfebbddafcbebeeedfdebddaaacabbbcfedbfcaddecf")  (str.++  "eede" C "fcdeccdaecbfdabceffadfaeaaefea" A "dafcbebeeedfdebddaaacabbbcfedbfcaddecf") ))
(assert (= (str.++  "bfcfbcaeeaadafdeddcfdddfdcebbfecfdacbbdaabdd" C "aeedaabebddecefaefcbcedabedeeecceaadbcbccbc")  (str.++  "bfcfbcaeeaadafdeddcfdddfdcebbfecfdacbbdaabdd" C "aeedaabebddecefaefcbcedabedeeecceaadbcbccbc") ))
(assert (= (str.++  "dbaedaeedacdbefebdecbcfbfcebaddbadeffccfefbfbcadeeceaaefceeceaeefbdaadefcdaececddbeebcaafa" "")  (str.++  "dbaedaeedacd" C "ebdecbcfbfcebaddbadeffccfefbfbcadeeceaaefceeceaeefbdaadefcdaececddbeebcaafa") ))
(assert (= (str.++  "eaebccfcadedbcefaceacceacfadebf" C "fedfacbfdceddeaccedfceeaadbcaddbdbccfefcbaabcbdcebcebdbe")  (str.++  "eaebccfcadedbcefaceacceacfadebfbeffedfacbfdceddeaccedfceeaadbcaddbdbccfefcbaabcbdcebcebdbe" "") ))
(assert (= (str.++  "ebdfbaeefeedbbddeafceeaebaaeaaebfdbdabbeaadccccacccbbecb" C "bbbccccecfdbcbfeebfeecbcdcfdbae")  (str.++  "ebdfbaeefeedbbddeafceeaebaaeaaebfdbdabbeaadccccacccbbecb" C "bbbccccecfdbcbfeebfeecbcdcfdbae") ))
(assert (= (str.++  "dbcebaecdaedcdcdbbcebbfeccbcfceedfddfaffebeeaafcebfcdcbdaeafcefabefbffbcddcbadbfaadfbaafdf" "")  (str.++  "dbcebaecdaedcdcdbbcebbfeccbcfceedfddfaffebeeaafcebfcdcbdaeafcefa" C "bffbcddcbadbfaadfbaafdf") ))
(assert (= (str.++  "ceecdfbeecbeadacbcedeeaedfadcafebbdbdefbfebefdfdccbdafcdcfbcdccaecfafabbabceacbdaaebaafefe" "")  (str.++  "ceecdfbeecbeadacbcedeeaedfadcafebbdbdefbfe" C "dfdccbdafcdcfbcdccaecfafabbabceacbdaaebaafefe") ))
(assert (= (str.++  "cfdeeaeedffbddbafdbdfbaefacceaccfabdecaacaeaaaefbfacbffdedbcceeecacffabdfcfafafdccfd" C "fbd")  (str.++  "cfdeeaeedffbddbafdbdfbaefacceaccfabdecaacaeaaaefbfacbffdedbcceeecacffabdfcfafafdccfd" C "fbd") ))
(assert (= (str.++  "fbccfaddcabdedfac" C "beccddcfcfabfeecdebedbdaeafefbbcfcbdfefcdafdcffedafbebabbadbeebcfdeaec")  (str.++  "fbccfaddcabdedfacbefbeccddcfcfabfeecdebedbdaeafefbbcfcbdfefcdafdcffedafbebabbadbeebcfdeaec" "") ))
(assert (= (str.++  "ddeebdabacacbaddeacebaecebfcadcacdcbdebaacbefcfdaefddaabcbbacbbbedaadfccadfdedebcbfbdbcfaa" "")  (str.++  "ddeebdabacacbaddeacebaecebfcadcacdcbdebaac" C "cfdaefddaabcbbacbbbedaadfccadfdedebcbfbdbcfaa") ))
(assert (= (str.++  "cafdccafeacbcffeb" C "adedaabbdeaaedddbbdadeecdfaceadedbcecbabdfdacbbddacdefbfedafbcefadecfc")  (str.++  "cafdccafeacbcffeb" C "adedaabbdeaaedddbbdadeecdfaceadedbcecbabdfdacbbddacdefbfedafbcefadecfc") ))
(assert (= (str.++  "fdacacbbdbdacfcdbfcdbc" C "eacfddbfcafcfacdddecbceacdcebfcafcdcacbeccfbfcafddccbfeeedebeeefe")  (str.++  "fdacacbbdbdacfcdbfcdbc" C "eacfddbfcafcfacdddecbceacdcebfcafcdcacbeccfbfcafddccbfeeedebeeefe") ))
(assert (= (str.++  "fccafafcefeeedebfeadadddecefcdde" C "cdfdbfebdcfcfdfadbebdbebfbcadfbabafceefdcafbabcccfbaafb")  (str.++  "fccafafcefeeedebfeadadddecefcddebefcdfdbfebdcfcfdfadbebdbebfbcadfbabafceefdcafbabcccfbaafb" "") ))
(assert (= (str.++  "fdcecbdbabeeeaebcfffcabafabddbcfbaf" C "afbabcfaddfaedeaceafdffbeddaffaddabaefbeccfafbcdddaf")  (str.++  "fdcecbdbabeeeaebcfffcabafabddbcfbafbefafbabcfaddfaedeaceafdffbeddaffaddabaefbeccfafbcdddaf" "") ))
(assert (= (str.++  "dabdfacdfedddeefdafbcf" C "cbccdfbdcbcbecdbbfbaafaadddeedaebcefabffcbbbcabfbacbcebeaceacabfa")  (str.++  "dabdfacdfedddeefdafbcfbefcbccdfbdcbcbecdbbfbaafaadddeedaebcefabffcbbbcabfbacbcebeaceacabfa" "") ))
(assert (= (str.++  "cbffcbbbbabfddeaaaccbbdacdaaecdfbccaaccbeddcaffdffbdbabddcdeaee" C "edcecdacedebcdefbbedbbad")  (str.++  "cbffcbbbbabfddeaaaccbbdacdaaecdfbccaaccbeddcaffdffbdbabddcdeaeebefedcecdacedebcdefbbedbbad" "") ))
(assert (= (str.++  "ccbbbfafbafcdadcea" C "aaeddfffffbcfedacbdcefdaceebdecaabd" C "beddccfbbabcebbeeacfedcfdccfbbe")  (str.++  "ccbbbfafbafcdadceabefaaeddfffffbcfedacbdcefdaceebdecaabdbefbeddccfbbabcebbeeacfedcfdccfbbe" "") ))
(check-sat)
(get-model)
