(set-logic QF_S)
(declare-fun F () String)
(declare-fun E () String)
(declare-fun C () String)
(assert (= (str.++  "bdcbbacbbacaccddc" F "aacadbbabbcdaaccdbacd")  (str.++  "bdcbbacbbacaccddc" E "acadbbabbcdaaccdbacd") ))
(assert (= (str.++  "ccdcccbcdd" C "b" C "abbbaac" F "aabababcdbdbcaabc")  (str.++  "ccdcccbcdd" E "abbbaacdbbdcadaaadbdaabababcdbdbcaabc") ))
(assert (= (str.++  "aabdaaaaccadaaaadc" C "cdcbbacccbbdabdbaabdcccbabadcddad")  (str.++  "aabdaaaaccadaaaadcbddcdcbbacccbbdabdbaabdcccbabadcddad" "") ))
(assert (= (str.++  "abbbadacaadabddabddabcbabcbadbccbadddbbbbbcabbdacbcbdd" "")  (str.++  "abbbadacaada" C "a" C "abcbabcbadbccbadddbbbbbcabbdacbc" C) ))
(assert (= (str.++  "cbcbcadbabbaacb" C "dacbabbaaadbabdbabbddb" C "ccabbbbccad")  (str.++  "cbcbcadbabbaacb" C "dacbabbaaadbabdbab" E "ccabbbbccad") ))
(assert (= (str.++  "abcdadabbcbbbddbcdaaba" C "bdabddaaddcaddcaddcbbbdcddaaa")  (str.++  "abcdadabbcbb" C "bcdaaba" C "bdabddaaddcaddcaddcbbbdcddaaa") ))
(assert (= (str.++  "cddcbdcadcddbdadc" C "cbbdbaccbdacdbbbaddadadadacdaabbad")  (str.++  "cddcbdcadcddbdadcbddcbbdbaccbdacdbbbaddadadadacdaabbad" "") ))
(assert (= (str.++  "aadccdabaddabdcdbbabcaabbdcbcbadbbbdccabbddbbaadddaabc" "")  (str.++  "aadccdabaddabdcdbbabcaabbdcbcbadbbbdccab" C "bbaadddaabc") ))
(assert (= (str.++  "cddccbdbabdbaabcbabacbdbddccdbaddcbddadddcd" C "dccadbab")  (str.++  "cddccbdbabdbaabcbabacbdbddccdbaddcbddadddcd" C "dccadbab") ))
(assert (= (str.++  "baadbdbbbdc" C "cabcabbdaabdbacbabbaabbccdbabdbacccaabdb")  (str.++  "baadbdbbbdc" C "cabcabbdaabdbacbabbaabbccdbabdbacccaabdb") ))
(assert (= (str.++  "dbdbacaddadcbdbaacbcdcaddbbdaadaaccbcaadbdddddadddabdc" "")  (str.++  "dbdbacaddadcbdbaacbcdcaddbbdaadaaccbcaad" C "dddadddabdc") ))
(assert (= (str.++  "bdadcaccbabbbbabbaabddbcdcadbdcadcacbdbaabacdccdadbbac" "")  (str.++  "bdadcaccbabbbbabbaa" C "bcdcadbdcadcacbdbaabacdccdadbbac") ))
(assert (= (str.++  "acaacdcbbccbbcbbcbbabaddd" C "cdbadbbbaddbccbbdcdabdddac")  (str.++  "acaacdcbbccbbcbbcbbabadddbddcdbadbbbaddbccbbdcda" C "dac") ))
(assert (= (str.++  "dcccdcacdacacabdabdacdcddbabaabddbbbbacaaabd" C "dcbaaca")  (str.++  "dcccdcacdacacabdabdacdcddbabaa" C "bbbbacaaabdbdddcbaaca") ))
(assert (= (str.++  "cccbdabbaadbccbdaadc" C "dcccbaaaaabcadadbdaacadbccbadcb")  (str.++  "cccbdabbaadbccbdaadcbdddcccbaaaaabcadadbdaacadbccbadcb" "") ))
(assert (= (str.++  "bcccbdc" C "aacbcaccdbdaddabdbbabaacccaabbcdbdaccddaddbb")  (str.++  "bcccbdc" C "aacbcaccdbdaddabdbbabaacccaabbcdbdaccddaddbb") ))
(assert (= (str.++  C "aaabacdaccbbbaadcdadcbccbcdbcbbaaacbccbbabbcbbcdccd" "")  (str.++  C "aaabacdaccbbbaadcdadcbccbcdbcbbaaacbccbbabbcbbcdccd" "") ))
(assert (= (str.++  "bacadcbddabcabbdcddacccbadbddcbdc" C "adcccddcdddacccaaa")  (str.++  "bacadc" C "abcabbdcddacccbad" C "cbdc" C "adcccddcdddacccaaa") ))
(assert (= (str.++  "bac" C "aaaadacddccbcbbcadbccaaacacabcaabbcbdadbcdacacaa")  (str.++  "bacbddaaaadacddccbcbbcadbccaaacacabcaabbcbdadbcdacacaa" "") ))
(assert (= (str.++  "cdcbdbddbacdcdcacdaabdaaaddacbdccdaddbcaaaacabdaccacdb" "")  (str.++  "cdcbd" C "bacdcdcacdaabdaaaddacbdccdaddbcaaaacabdaccacdb") ))
(assert (= (str.++  "bbbbcbcdaabcdaabddcbcaaababdbdcaacacbddabbbabaaaddbdba" "")  (str.++  "bbbbcbcdaabcdaabddcbcaaababdbdcaacac" C "abbbabaaaddbdba") ))
(assert (= (str.++  "ccdcbacbdacdadcdaaabcccaadbabaaac" C "aaaaccdaacbbcdbbbd")  (str.++  "ccdcbacbdacdadcdaaabcccaadbabaaac" C "aaaaccdaacbbcdbbbd") ))
(assert (= (str.++  "ddbbbdcdbdbdcdcd" C "adaabdcdcdccbddacbaaadcbbcaaddaacca")  (str.++  "ddbbbdcdbdbdcdcdbddadaabdcdcdccbddacbaaadcbbcaaddaacca" "") ))
(assert (= (str.++  "bddcabccbaabbadbbbdc" C "dabaaccacbadbcbbdcdcdbbdbcadbdd")  (str.++  "bddcabccbaabbadbbbdcbdddabaaccacbadbcbbdcdcdbbdbcadbdd" "") ))
(assert (= (str.++  "ddcbdccbabbbddcbdbadccccbcbdbccbbccbbdcbdbcbdcbddbcbac" "")  (str.++  "ddcbdccbabb" C "cbdbadccccbcbdbccbbccbbdcbdbcbdcbddbcbac") ))
(assert (= (str.++  "dadaabccaabddbdcdcbaacacccdcdabdddbddbbaacdabccdcadabd" "")  (str.++  "dadaabccaabddbdcdcbaacacccdcdabddd" C "bbaacdabccdcadabd") ))
(assert (= (str.++  "ddacbbcacbabaccbbdbadbdccaaabcbddaacbaccddcbabddbcdabc" "")  (str.++  "ddacbbcacbabaccbbdbadbdccaaabc" C "aacbaccddcbabddbcdabc") ))
(assert (= (str.++  "abbdadcabdbbcdbcdabdcbd" C "acdcbbaddbccdbaadbccbccbdaca")  (str.++  "abbdadcabdbbcdbcdabdcbd" C "acdcbbaddbccdbaadbccbccbdaca") ))
(assert (= (str.++  "bbbdcbddbccbbaddbbababbdbaccabddbbcbcdcabbbdabcddbaaca" "")  (str.++  "bbbdcbddbccbbaddbbababbdbacca" C "bbcbcdcabbbdabcddbaaca") ))
(assert (= (str.++  "dabbdd" C "bdabbbdac" C "bbdaddcabbabaaaabdcbcccdbbbccbdaa")  (str.++  "dab" C "bddbdabbbdacbddbbdaddcabbabaaaabdcbcccdbbbccbdaa") ))
(assert (= (str.++  "bdcab" C "a" C "babbbadaddaddaadcadcacdabbcabbadccaadcddcb")  (str.++  "bdcabbddabddbabbbadaddaddaadcadcacdabbcabbadccaadcddcb" "") ))
(assert (= (str.++  "abbbbbadaddaddbcadcccccdacdddcdbaabcdcbcadbcdadd" C "dab")  (str.++  "abbbbbadaddaddbcadcccccdacdddcdbaabcdcbcadbcdadd" C "dab") ))
(assert (= (str.++  "bccdbdcabbadabcbdbbcdbccdc" C "bdbdbadadcdbbdaaadacdaadd")  (str.++  "bccdbdcabbadabcbdbbcdbccdc" C "bdbdbadadcdbbdaaadacdaadd") ))
(assert (= (str.++  "a" C "abbadbcbdcaccaddcbbaabbccdbddadad" C "abbcbabddbaaac")  (str.++  "abddabbadbcbdcaccaddcbbaabbccdbddadadbddabbcbabddbaaac" "") ))
(assert (= (str.++  "caabcababccbcdaccdd" C "adaacacacbaabdabdbaccacdccddddac")  (str.++  "caabcababccbcdaccdd" C "adaacacacbaabdabdbaccacdccddddac") ))
(assert (= (str.++  "abcbbcbbbbcbbdcbbbaccadbbbdaabc" C "abbdcccdcdbdaadbabcb")  (str.++  "abcbbcbbbbcbbdcbbbaccadbbbdaabcbddabbdcccdcdbdaadbabcb" "") ))
(assert (= (str.++  "adcddabbaabbddbabcdcadaaaddb" C "ccacdadba" C "cdbcddccddb")  (str.++  "adcddabbaab" C "babcdcadaaaddbbddccacdadba" C "cdbcddccddb") ))
(assert (= (str.++  "cdcdddaabdbbddabaacacddbbacadcadacddbabadada" C "ccacbbd")  (str.++  "cdcdddaabdbbddabaacacddbbacadcadacddbabadada" C "ccacbbd") ))
(assert (= (str.++  "abbdbcbbdcdccccadaacdcbbdadccbadbdcadcdbcddabcbdcd" C "d")  (str.++  "abbdbcbbdcdccccadaacdcbbdadccbadbdcadcdbcddabcbdcdbddd" "") ))
(assert (= (str.++  "bbbadaccaadcdcdbaacdacba" C "bbbdacdcadadbdaccdccaadddbc")  (str.++  "bbbadaccaadcdcdbaacdacbabddbbbdacdcadadbdaccdccaadddbc" "") ))
(assert (= (str.++  "dcacabaccabcaabdbbcbddbccadbacccbaaddcbcdcdbaabdaaccad" "")  (str.++  "dcacabaccabcaabdbbc" C "bccadbacccbaaddcbcdcdbaabdaaccad") ))
(assert (= (str.++  "cbdcaadbccaccddbdcddbcacacadcaccbdcddddccdbabdcbdabbdd" "")  (str.++  "cbdcaadbccaccddbdcddbcacacadcaccbdcddddccdbabdcbdab" C) ))
(assert (= (str.++  "acdbadc" C "baddcdcbadbcccbabbdccacadbbaccaddadbdcabacda")  (str.++  "acdbadc" C "baddcdcbadbcccbabbdccacadbbaccaddadbdcabacda") ))
(assert (= (str.++  "addaddbcabcdabaacdb" C "dbcdcaaadcbdbdabcbcccbbcbaacaddd")  (str.++  "addaddbcabcdabaacdb" C "dbcdcaaadcbdbdabcbcccbbcbaacaddd") ))
(assert (= (str.++  "bbcabaddcbcadcacdbacabbccbdddba" C "cddddccddcdadcdcbadc")  (str.++  "bbcabaddcbcadcacdbacabbccbdddba" C "cddddccddcdadcdcbadc") ))
(assert (= (str.++  "aa" C "ddacccdacbcddcaacabbdaadacbabcdcacbbdcdddbbbcacbb")  (str.++  "aabddddacccdacbcddcaacabbdaadacbabcdcacbbdcdddbbbcacbb" "") ))
(assert (= (str.++  "ccadcbaaddba" C "accdbccbdaaaabadcaddddbccaabcacbdada" C)  (str.++  "ccadcbaaddba" C "accdbccbdaaaabadcaddddbccaabcacbdadabdd") ))
(assert (= (str.++  "babaaacdccbabcaddbcdadddccbacddbcdbbdbba" C "aadadbbbbbb")  (str.++  "babaaacdccbabcaddbcdadddccbacddbcdbbdbba" C "aadadbbbbbb") ))
(assert (= (str.++  "aaccabdbdbbabdbdbbddcccb" C "dddccbabacdabaaadacbadcbdaa")  (str.++  "aaccabdbdbbabdbdb" C "cccb" C "dddccbabacdabaaadacbadcbdaa") ))
(assert (= (str.++  "bcdbcbacbdddccaccdbbddabbdaacaadcadbbaabcccacaabbaddbc" "")  (str.++  "bcdbcbac" C "dccaccdb" C "abbdaacaadcadbbaabcccacaabbaddbc") ))
(assert (= (str.++  "adcaccdcdabc" C "daadbaccccdaccadaaaaadbbbaacaccacdccadd")  (str.++  "adcaccdcdabcbdddaadbaccccdaccadaaaaadbbbaacaccacdccadd" "") ))
(assert (= (str.++  "acbdddcbabbcbabacbadabbdbdabbbbaabcdcdbccbaccbbcbcabbb" "")  (str.++  "ac" C "dcbabbcbabacbadabbdbdabbbbaabcdcdbccbaccbbcbcabbb") ))
(assert (= (str.++  "bbccaddddbadcaacaacdbcacaacadadb" C "ccdbadcccbbcdbcbbda")  (str.++  "bbccaddddbadcaacaacdbcacaacadadb" C "ccdbadcccbbcdbcbbda") ))
(assert (= (str.++  "cbdaddddbbacabbbabbb" C "cbb" C "caccadaabcbccadbaaccbbaac")  (str.++  "cbdaddddbbacabbbabbbbddcbb" C "caccadaabcbccadbaaccbbaac") ))
(assert (= (str.++  "cdaacbaadb" C "dcaaccabddbcbbcaddbbcdbdbdcbdbdbbaaddadbc")  (str.++  "cdaacbaadb" C "dcaaccabddbcbbcaddbbcdbdbdcbdbdbbaaddadbc") ))
(assert (= (str.++  "abcaabadacdcaaadbdbadccaaabaabcccbcbcdbdbbbdddcbaabbcd" "")  (str.++  "abcaabadacdcaaadbdbadccaaabaabcccbcbcdbdbb" C "dcbaabbcd") ))
(assert (= (str.++  "cbadadadba" C "cbbbbabdadbbddcdddccbbdbcbaadadbbbcbbbbbc")  (str.++  "cbadadadbabddcbbbbabdadbbddcdddccbbdbcbaadadbbbcbbbbbc" "") ))
(assert (= (str.++  "ccdadabdbbadac" C "bbdbbdadddbcdddbaadbacccbdcabccccccaa")  (str.++  "ccdadabdbbadac" C "bbdbbdadddbcdddbaadbacccbdcabccccccaa") ))
(assert (= (str.++  "a" C "bcacbadbabdcbacbddadaccddcdacabbccdbcddcccbbcdabac")  (str.++  "a" C "bcacbadbabdcbac" C "adaccddcdacabbccdbcddcccbbcdabac") ))
(assert (= (str.++  "bbcacbabdbddbccbbdbbdcadaadcdacddabcaacbadcadcabdcacda" "")  (str.++  "bbcacbabd" C "bccbbdbbdcadaadcdacddabcaacbadcadcabdcacda") ))
(assert (= (str.++  "aacddbbcccdddacdcddcbddaccddddbcbadaadccadbcdccaaabddb" "")  (str.++  "aacddbbcccdddacdcddc" C "accddddbcbadaadccadbcdccaaa" C "b") ))
(check-sat)
(get-model)
