Variables {CDA}
Terminals {cabd}
Equation: cdbbdbbbbacDbcddccbbb = cdbbdbbbbacbbcbdabbCbbb
Equation: aadabbbdaadcbbdbdcdbcccdacAbbcbccacccadbbc = aadabbbdaadcbbdbdcdbcccdacAbbcbccacccadbbc
Equation: ddbddccbddccbbddbabbaaaabaaacbbbcbbaddaaAc = ddbddccbddccbbddbabbaaaabaaacbbbcbbaddaaAc
Equation: dccbacbbaadabAdabdcbacadcbdcbacbbcacbdbadc = dccbacbbaadababbbbadabdcbacadcbdcbacbbcacbdbadc
Equation: dcaaabbbbabbdbcbdabaccbaabdaacdbddbcdddcbaabcaa = dcaaAbbdbcbdabaccbaabdaacdbddbcdddcbaabcaa
Equation: ababbbbaaabbdbbabacadcbbabcccbddbbddacccbbcddcc = abAaabbdbbabacadcbbabcccbddbbddacccbbcddcc
Equation: aaaaddddbbAabacabcdbcaaaacacddcdcdccdbaadd = aaaaddddbbAabacabcdbcaaaacacddcdcdccdbaadd
Equation: cbcbaaddbaaaacbdccddcaccdbcbcabccdacAdaada = cbcbaaddbaaaacbdccddcaccdbcbcabccdacabbbbadaada
SatGlucose(100)