(set-logic QF_S)
(declare-fun C () String)
(declare-fun A () String)
(assert (= (str.++  "bbadbd" A "caccbcbaaacbdcdaad" C "cdcd")  (str.++  "bbadbdccdaccaccbcbaaacbdcdaadcaacbbcaaadbdadcaccbdbbdadcdcd" "") ))
(assert (= (str.++  "aaaddccacbcadcaabaaacdcaacbdddccaccabca" A "dbdcbcdaadbdccc")  (str.++  "aaaddccacbcadcaabaaacdcaacbdddccaccabcaccdacdbdcbcdaadbdccc" "") ))
(assert (= (str.++  "dcabaaccdbaddccbdcbccaacadadadccbdcaaacadbaabaccdaccdaaadcd" "")  (str.++  "dcabaaccdbaddccbdcbccaacadadadccbdcaaacadbaaba" A "cdaaadcd") ))
(assert (= (str.++  "abaaddabdbbbadbcddcbb" A "ddaddddbcdddbccabadbdcadcbbdbbaaa")  (str.++  "abaaddabdbbbadbcddcbb" A "ddaddddbcdddbccabadbdcadcbbdbbaaa") ))
(assert (= (str.++  "bdbab" A "dcacdcbcdacaabbbdadaaaabadcddcbbadbacabbddbbcdcba")  (str.++  "bdbabccdacdcacdcbcdacaabbbdadaaaabadcddcbbadbacabbddbbcdcba" "") ))
(assert (= (str.++  "acbddbbaabdddbabdcdadacacbaadbdbbccaaccdacdbaaaaccdbdddbaaa" "")  (str.++  "acbddbbaabdddbabdcdadacacbaadbdbbccaa" A "dbaaaaccdbdddbaaa") ))
(assert (= (str.++  "acdcaddbdcabba" A "bcdbcbcbcdbbcccacaabbacddabbdbddcdbddcbc")  (str.++  "acdcaddbdcabbaccdacbcdbcbcbcdbbcccacaabbacddabbdbddcdbddcbc" "") ))
(assert (= (str.++  "dbddcadacdbbbdbacaabccdbcb" A "ccaaddbaccdcaabcbcddacbadcbc")  (str.++  "dbddcadacdbbbdbacaabccdbcbccdacccaaddbaccdcaabcbcddacbadcbc" "") ))
(assert (= (str.++  "cbacdaaaddbaaabdaddcbbdcdcdbbaccddbbaccdacbbccbddabacabaaad" "")  (str.++  "cbacdaaaddbaaabdaddcbbdcdcdbbaccddbba" A "bbccbddabacabaaad") ))
(assert (= (str.++  "badab" A "baaabbcccacdccdadddabddbaabcdbcaaccccabbdccbabdda")  (str.++  "badabccdacbaaabbcccacdccdadddabddbaabcdbcaaccccabbdccbabdda" "") ))
(assert (= (str.++  "cbbdbbbbddaacdd" A "bccdadcdccaccdbbdbaccaddcabcbbbcbbcabcc")  (str.++  "cbbdbbbbddaacddccdacbccdadcdccaccdbbdbaccaddcabcbbbcbbcabcc" "") ))
(assert (= (str.++  "acaacdcbadbbccdaadbabcccbdadaccdacaabbcbbcabdcbbbadbacadaca" "")  (str.++  "acaacdcbadbbccdaadbabcccbdada" A "aabbcbbcabdcbbbadbacadaca") ))
(assert (= (str.++  "dddcaabdaabdccccbcdddbbdbabdccbacddacbdbbabdaa" A "adcdadcb")  (str.++  "dddcaabdaabdccccbcdddbbdbabdccbacddacbdbbabdaa" A "adcdadcb") ))
(assert (= (str.++  "bcdcadbbbaaacdddbcccbbbdadabcdacdaa" A "abadbacbabacbacadab")  (str.++  "bcdcadbbbaaacdddbcccbbbdadabcdacdaa" A "abadbacbabacbacadab") ))
(assert (= (str.++  "cdaababacdbcdcdccabaaadabadaddbacbbdbbbbc" A "dbbbaabccaabb")  (str.++  "cdaababacdbcdcdccabaaadabadaddbacbbdbbbbcccdacdbbbaabccaabb" "") ))
(assert (= (str.++  "acbddcaabdbddbbbaaabdaabbacabaabbaccadbddaccbdacccbcab" A)  (str.++  "acbddcaabdbddbbbaaabdaabbacabaabbaccadbddaccbdacccbcab" A) ))
(assert (= (str.++  "cbcadcadaacadaddbcccaaabcbdbdabbddaccdcabcdddbdb" A "acacdd")  (str.++  "cbcadcadaacadaddbcccaaabcbdbdabbddaccdcabcdddbdbccdacacacdd" "") ))
(assert (= (str.++  "adbbccbacdccbabcbbadcccabcbcccbbdcbccdacacbcadadbdacdcaaacd" "")  (str.++  "adbbccbacdccbabcbbadcccabcbcccbbdcb" A "acbcadadbdacdcaaacd") ))
(assert (= (str.++  "abbccdaccdbdadcbcccbadbbdbdccabcbbbaaccddbacaaaadabdbdbdccb" "")  (str.++  "abb" A "cdbdadcbcccbadbbdbdccabcbbbaaccddbacaaaadabdbdbdccb") ))
(assert (= (str.++  "cddddcdabadabccccdbcbdacdcbbaaabcadacbad" A "bdabdacdaaccdc")  (str.++  "cddddcdabadabccccdbcbdacdcbbaaabcadacbad" A "bdabdacdaaccdc") ))
(check-sat)
(get-model)
