(set-logic QF_S)
(declare-fun B () String)
(declare-fun E () String)
(declare-fun A () String)
(declare-fun C () String)
(assert (= (str.++  "bbcdcbbcecacdbeabdcbabbd" B "badeedaccabaddcadcddbe")  (str.++  "bbcdcbbc" A "dcbabbdcdabedb" C "deedaccabaddcadcddbe") ))
(assert (= (str.++  "ccea" B "cdcadabbbdecceecbeceaece" E "beacecabeaaeaebedaac" B "dcdcdcac")  (str.++  "cceabecdcadabbbdecc" C "c" B "acecabeaaeaebedaac" B "dcdcdcac") ))
(assert (= (str.++  "eccaeaadedaadeaadecbddaaecabaeaebbdaced" B "cdbccabbaedcacbadaadebcabdcacddbca")  (str.++  "eccaeaadedaadeaadecbddaaecabaeaebbdacedbecdbccabbaedcacbadaadebcabdcacddbca" "") ))
(assert (= (str.++  "dacecdcdebddcdddebadeebadbaaeadccbcaaaecbcadeeaebbbbbeccea" B "cacdebebda" B "bdc")  (str.++  "dacecdcdebddcdddebadeebadbaaeadccbcaaaecbcadeeaebbbb" B "ccea" B "cacde" B "bda" B "bdc") ))
(assert (= (str.++  "bccebdacdbccadecccbdecbbdddbadabbacceadbcacaebacbdcdeecadacdccaadececbce" B "b")  (str.++  "bccebdacdbccadecccbdecbbdddbadabbacceadbcacaebacbdcdeecadacdccaadececbcebeb" "") ))
(assert (= (str.++  "eaaeddccccaecdbcdbddbeaccbabaddcdebdbbbbccaebeeedbdabeebdeccbcdbdaeebcbbeee" "")  (str.++  "eaaeddccccaecdbcdbdd" B "accbabaddcdebdbbbbccae" B "eedbdabeebdeccbcdbdaeebcbbeee") ))
(assert (= (str.++  "aecaccbadbcebbcaeaeacadebadadebdecdaadeecdcbbcdbecdcdedaaddabaceeeadb" B "abbc")  (str.++  "aecaccbadbcebbcaeaeacadebadadebdecdaadeecdcbbcd" B "cdcdedaaddabaceeeadb" B "abbc") ))
(assert (= (str.++  "beecbadaaddaceeebadccdcdebebacadabaeeecccccbbcdcdcdebaebdcddecacdbccdeaabce" "")  (str.++  "beecbadaaddaceeebadccdcde" B "bacadabaeeecccccbbcdcdcdebaebdcddecacdbccdeaabce") ))
(assert (= (str.++  "ccddadddbdadcccddbaaadeaedddaabcadaebbacedeadbccedaccbccdaacaca" B "aabadbbcbc")  (str.++  "ccddadddbdadcccddbaaadeaedddaabcadaebbacedeadbccedaccbccdaacaca" B "aabadbbcbc") ))
(assert (= (str.++  "ceebdabbacbaacbacacdeabcbdccacaabbeeccbdedbceecdbabdbdeaaded" B "cbabdebccbaca")  (str.++  "ceebdabbacbaacbacacdeabcbdccacaabbeeccbdedbceecdbabdbdeaaded" B "cbabdebccbaca") ))
(assert (= (str.++  "aacaabaacbcaddddecdeaddccbbaeede" B "edebdadaaddceadbadaebdcdbadbacdbadcca" B B)  (str.++  "aacaabaacbcaddddecdeaddccbbaeedebeedebdadaaddceadbadaebdcdbadbacdbadccabebe" "") ))
(assert (= (str.++  "edacddcebbdcccedebeabdededeccdbdedcababacadabcbba" B "baacb" B "aabbdada" B "cbeabec")  (str.++  "edacddcebbdcccede" B "abdededeccdbdedcababacadabcbbabebaacb" B "aabbdada" B "c" B "abec") ))
(assert (= (str.++  "cdedbcdecedbbbbebcaaaccaabaacaddedeadbaeaddacadeacdaadebcbadbabcadbbedacaae" "")  (str.++  "cdedbcdecedbbbbebcaaaccaabaacaddedeadbaeaddacadeacdaadebcbadbabcadb" B "dacaae") ))
(assert (= (str.++  "edabbadebbbaabccccbaaa" B "daeea" B "aadbd" B "cebbdaeaabdaecbadaebcaeeeecbcddddaedb")  (str.++  "edabbadebbbaabccccbaaa" B "daeeabeaadbdbecebbdaeaabdaecbadaebcaeeeecbcddddaedb") ))
(assert (= (str.++  "ecbddba" B B "cdacedbadebecacaedbaddeeeeebdaedbbcecadebbbaaddcedecbdaceeadecac")  (str.++  "ecbddba" B B "cdacedbade" B "cacaedbaddeeeeebdaedbbcecadebbbaaddcedecbdaceeadecac") ))
(assert (= (str.++  "bdcacacbacdbcccdceacceaaebcbbbccdaadeceaebdebdacdacccaeacaadada" B "caacabaead")  (str.++  "bdcacacbacdbcccdceacceaaebcbbbccdaadeceaebdebdacdacccaeacaadadabecaacabaead" "") ))
(assert (= (str.++  "eddeeabedceabddbcdcbcad" B "aedceddabaccbba" B "ececbcaccacddeaabdacaea" B "aabcebac")  (str.++  "eddeea" B "dceabddbcdcbcad" B "aedceddabaccbba" B "ececbcaccacddeaabdacaeabeaabcebac") ))
(assert (= (str.++  "aeebabaaaecaedbbccaacdabbacccaaccaadebddccaaebbeddddcccdadeab" B "cea" B "bdacdcc")  (str.++  "aeebabaaaecaedbbccaacdabbacccaaccaadebddccaaebbeddddcccdadeab" B "ceabebdacdcc") ))
(assert (= (str.++  "abaeeaabbceaedadbdedddecbdbbaddbcbacdeecedceabdddcb" B "ddaaededdebddaabceddea")  (str.++  "abaeeaabbceaedadbdedddecbdbbaddbcbacdeecedceabdddcb" B "ddaaededdebddaabceddea") ))
(assert (= (str.++  "edbadcbdceabcdaabdbeccebdbbdbdccbcaeaecbebbdedddccdecaaeeca" B "eabcdeccdacaba")  (str.++  "edbadcbdceabcdaabdbeccebdbbdbdccbcaeaecbebbdedddccdecaaeeca" B "eabcdeccdacaba") ))
(assert (= (str.++  "bbccabdcedccbccdeeea" B "ecebde" B "aedeabbadceeeebceceddcdabcccedcdeadddbaedcdbc")  (str.++  "bbccabdcedccbccdeeeabeecebde" B "aedeabbadceeeebceceddcdabcccedcdeadddbaedcdbc") ))
(assert (= (str.++  "cadbddebaebbcbaeadcaeabbbacaacbcdaedaaecabdcebdacabdeacaaeaddbeceeeaedddaed" "")  (str.++  "cadbddebaebbcbaeadcaeabbbacaacbcdaedaaecabdcebdacabdeacaaeadd" B "ceeeaedddaed") ))
(check-sat)
(get-model)
