Variables {IFAJ}
Terminals {cab}
Equation: cabccabbaccbcFcabbc = cabccabbaccbccaAaabcJaaabaacbaacabbc
Equation: cbcbbaccaIcacbbbaacabacbbbbcabcaaaaaaabbbcabcbbabaabcabcbc = cbcbbaccaIcacbbbaacabacbbbbcabcaaaaaaabbbcabcbbabaabcabcbc
Equation: cbbIbcacccbaabccbacbbbbbacaccacaacacacbabcacccaacbbaacccaa = cbbbcbabbcacccbaabccbacbbbbbacaccacaacacacbabcacccaacbbaacccaa
SatGlucose(100)