Variables {CGA}
Terminals {cab}
Equation: aAAaaaCbAaAbbabbcbaacbacaabbabbAAbbbaAbaAb = aAAaaababccabbGcbaaAbaAaabbabbcAbbbacbacb
Equation: AAcaAbabAabaaAaaabaAbccaabAbcccacacacccaAbcbabaabaaaacabbbAbbccbabacA = cccaAbabcabaacaaabacbccaabAbAAcacaAaAcAaAbAbabaabaaaacabbbcbbccbabaAA
Equation: baaAbcbbaaaAbbbacaabcAbaaaabaAaabaAbbbbbbbbbAcccbaaccAcbAbabbAbbabbAb = baaAbcbbaaacbbbacaabccbaaaabaAaabaAbbbbbbbbbcAccbaacccAbcbabbcbbabbcb
Equation: abAcbcabAAAcbbbabaacbaaacacAAabbbAbacabbcbAabbbbacbcAbbbbcbcccacAbAab = abAcbcabAAccbbbabaaAbaaacacAAabbbcbaAabbAbAabbbbaAbccbbbbcbAccaAAbcab
Equation: AaaaAbcbccaAbbAacaaccacabbaaAaAaAbaaAbabbbbbbbabbaabbaacabcAaacaaAcAA = caaacbcbAcacbbAacaaccacabbaacaAacbaacbabbbbbbbabbaabbaacabAcaaAaaccAc
Equation: abccaabbabcbbbaAbbcbaaAAaabbaAaAAbababcbccaabbcbbbabaabbaAcbaacAcaaab = abcAaabbabAbbbacbbAbaaAAaabbaAaccbababAbccaabbAbbbabaabbaAcbaacccaaab
Equation: bbaaAccbbbAaaaabcabAccacaAacaaabccbaaabbcabaAbbbabaAcAAaabbbAabbabaAa = bbaaAAcbbbAaaaabcabcAcacaAacaaabAcbaaabbcabaAbbbabaAcAAaabbbcabbabaca
Equation: bAabaAbcbbbAbacbAAcAbcabbaAacAabaaAbAaabaAabbAaabAbbAacbccbAbbbaAbaca = bcabacbAbbbcbaAbcccAbcabbacacAabaaAbcaabacabbAaabAbbcaAbccbcbbbacbaca
SatGlucose(100)