(set-logic QF_S)
(declare-fun I () String)
(declare-fun F () String)
(declare-fun A () String)
(declare-fun J () String)
(assert (= (str.++  "cabccabbaccbc" F "cabbc")  (str.++  "cabccabbaccbcca" A "aabc" J "aaabaacbaacabbc") ))
(assert (= (str.++  "cbcbbacca" I "cacbbbaacabacbbbbcabcaaaaaaabbbcabcbbabaabcabcbc")  (str.++  "cbcbbacca" I "cacbbbaacabacbbbbcabcaaaaaaabbbcabcbbabaabcabcbc") ))
(assert (= (str.++  "cbb" I "bcacccbaabccbacbbbbbacaccacaacacacbabcacccaacbbaacccaa")  (str.++  "cbbbcbabbcacccbaabccbacbbbbbacaccacaacacacbabcacccaacbbaacccaa" "") ))
(check-sat)
(get-model)
