Variables {BHGFCD}
Terminals {cab}
Equation: bacbGcGbcGcCGCGbDcCbDCbcGcbbbbcCGCGabGGbbC = baGbGGGbGcBGCGbaaBbCaCbGGcbbbbBGaGCbcGbbC
Equation: bGCCaGabCGcDbGGbabGbCGCbGGcaGGaCacbCabbbbcG = bGCCaFCGcCCbGcbCbcbaFcGGCcBCacbaCbbbbGc
Equation: CcCacbCaGbbbbbbbGCbbcGbaCabCCCcccGbbGCCaCBG = acCCGbCacbbbbbbbFbGcbaCabCaCcGccbbGCCCCGac
Equation: ccabacCbCcbccGcbacCabbGbabcbCaGCCccCbbGCBaC = cFCGCbCcbcGcGbCGCCbbGbabGbaaGDcFbcCcCCa
Equation: bbacGcCCbacbbcCaaccbccBaaacCabGacbGbBabGbC = bbacccCabCcbbcCCCGcbcGcCCCacaCbcCGbGbcCabcba
Equation: GCGcCGbCCcBcGDCbccGbCGabbCbGaaGGbbCbGbacCG = cacGacbaaGGCcGaCCbGGcbacabbCbBaGGbbCbcbaBc
Equation: cbbaacCcaabcaaGGbGcbbcGDGGbbbCbCcbaCabGCcbb = GbbCacCcCCbcCCccbccbbGGCacGbbbCbaGbaCCbBcbb
Equation: CCGbaCbbbDCacbcCaccCaaababacbCbcCbabCGCbGCb = CCGbCCbbbaCCacbGCCccCDCbabaGbCbGCbCbaFcab
Equation: BCbGaGccCCGcbaGGBGDcbGCbCGGcbcbCbcGbcbGCG = cCCbcCcGGCaGcbaGcBBCGbFCcGGbcbCbGGbGbBc
Equation: bbabCcaCaGCGcbbGbGcccCbcbccCCbCGcBbGbGbGBb = bbCbacaCaBGcbbcbcccFcbGcCCbacGcabGbcbGcCb
Equation: bGbCcccGGCbDbDcCbbbcbbaabCbGbBbbCGCbabCbb = bcbaGcGGBbCabCCFbbcbbCCbCbcbcCbbCGabababb
Equation: bGbbCcabGbCbbabCbGbcCCCGGbaGCGcBbCCCaCCaabC = bGbbCGCbGbCbbababGbGCDGGbCcCcGGabCCaaaCCCba
Equation: GbbDbbabaGGaCCaCbCbabbbGcGGGbbbbbbCCaGcbBb = GbbCCbbabCccaCCCabCbabbbcGGcGbbbbbbCaCccbBb
Equation: aCcGCCGcccGGDbaGBbBccbbbbbbcGCGbbbGbbCCbc = CaGGCacGGGcGCabaGFGaGcbbbbbbGBGbbbGbbaabc
Equation: bCCGCcGbBbGbcbGcCabbcGbbbGcbBbGCbCCCccCGab = bCaBGcbFcbcbcGCCbbGGbbbccbcCbFaCCcBF
Equation: bbbGGGaCcCCabccbCbcbbGGCCBbaGGGbbcbCGBcbCC = bbbcGGaCBCabccbabcbbGGaCcCbCGccbbcbCGcCcbCC
Equation: aGCcCbabbbbCCaabbCcGcaaaBCcGCCcaaBbbGCbbCb = CBFabbbbaCCabbaGGcCaCGDcGaCGCaFbcabbCb
Equation: abbcbbGGcbccccGCGGbCCabBbabcGbBbbGbbcGcbGb = abbGbHccGCGcbCCCbGCbabGcbGCbbcbbGcGbGb
Equation: GbcGaabababbGBbaCccbbCcGbGcCGaGGcbDCaCbCbG = cbGGCabCbCbbGGabaaccbbaGcbGBcCcccbCCaCababG
Equation: GbGbGbGcbCabCbCaGCabDcccbGaGbbbBbbaCBCCca = GbcbcbcGbaCbabCacaCbaCccGbGacbbbBbbCCcCaCB
Equation: aCGbCCCbaabGbcbabCabCbabbCbGBbFBCacGbcbC = aCcbaCabCabcbGbCbDbababbabcFFGCaCGcbGbC
Equation: cGGCabbbGGbbbaCbGGCbbbGbbbabbbGbbCbbbaBccCc = ccGaCbbbcGbbbCCbGFbbcbbbCbbbcbbCbbbCGacGCc
Equation: aabbcbaGGbGCGGCccCCGbaCbbaGacbaacCaCbbcccbB = CCbbGbaGGbGCGcaGGCacbCCbbCGCcbCCcCaabbGGcbB
Equation: CabCbcabbacbCabCacbcbbGGCbbGGGCDbbcbcBGGbb = CCbabGCbbacbCabaCGbGbbccabbccBaCbbGbGcCcGbb
Equation: bcbbcbcbbCGcaGCaBCCbbCcCbCccbDbaabaaCccGbG = bcbbGbcbbCcBcCCGaCabbCFaGGbCabDbCCCGccbc
Equation: cCGCbbbCGGCcbbcbbGbGaCaCbCGbbGcGbCaCCbbBaab = GCFbbCcGCGbbcbbGbBaCCbCGbbcGGbaCCabbGCCab
Equation: GGcCbCabGbbccbbbCDbGbcccbGcaccbGbaGDbbCGB = GGFCabcbbGcbbbaaabGbGGcbcGaGcbcbacCabbCcGC
Equation: CbbCGccbcGGccGbbCGGbGGBbbcGcBaCCaGbbGCbbGb = CbbaGGcbcGGGccbbaGcbGcFbcccGCCCCaGbbFbcb
SatGlucose(100)