(set-logic QF_S)
(declare-fun B () String)
(declare-fun E () String)
(declare-fun G () String)
(declare-fun F () String)
(declare-fun A () String)
(declare-fun C () String)
(declare-fun D () String)
(assert (= (str.++  C B D)  (str.++  E E B "aaaaaaaaaaaaaaaaaaa") ))
(assert (= (str.++  A D D)  (str.++  G "aaaaaaaaaaaaaaaaaaaaa" E "aaaaa") ))
(assert (= (str.++  C "aaaaaaaaa" A "aaaaaaaa")  (str.++  G "aaaaaaaaaaaaaaaaaaaaa" E "aaaaa") ))
(assert (= (str.++  A A "aaaaaaaa")  (str.++  G E "aaaaaaaaaaaaaaaaaaaaaaaaaa") ))
(assert (= (str.++  E E "aa" A "aaaaaaaa")  (str.++  "aaaaaaaaaaaaaaaaaaaaa" E "aaaaaaaaaaaaaaaaaaaaa" E "aaaaaaaaaaaa") ))
(assert (= (str.++  B "aaaaaaaaa" A "aaaaaaaa")  (str.++  "aaaaaaaaaaaaaaaaaaaaa" E E E "aaaaaaaaaaaa") ))
(assert (= (str.++  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" A "aaaaaaaa")  (str.++  G E E "aaaaa") ))
(assert (= (str.++  A E "aaaaa" D)  (str.++  G E E "aaaaa") ))
(assert (= (str.++  A A "aaaaaaaa")  (str.++  "aaaaaaaaaaaaaaaaaaaaa" E A "aaaaaaaaaa") ))
(assert (= (str.++  E E "aaaaaaaaaa" D "aaaaaaaaaaaaaaaaaa")  (str.++  E B "aaaaaaa" E "aaaaaaaaaaaa") ))
(assert (= (str.++  B "aaaaaaaaa" A "aaaaaaaa")  (str.++  E C B "aaaaa") ))
(assert (= (str.++  C E "aaaaa" D "aaaaaaaaa")  (str.++  G "aaaaaaaaaaaaaaaaaaaaa" E "aaaaa") ))
(assert (= (str.++  "aaaaaaaaaaaaaaaaaaaaa" E "aa" A "aaaaaaaa")  (str.++  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" E "aaaaaaaaaaaa") ))
(assert (= (str.++  B "aaaaaaaaa" A "aaaaaaaa")  (str.++  G "aaaaaaaaaaaaaaaaaaaaa" E "aaaaa") ))
(assert (= (str.++  B B D)  (str.++  G "aaaaaaaaaaaaaaaaaaaaa" E "aaaaa") ))
(assert (= (str.++  A A "aaaaaaaa")  (str.++  G C "aaaaaaaaaaaa") ))
(assert (= (str.++  B B "aaaaaaaaaaaaaaaaaaaaaaaaaa")  (str.++  E "aaaaaaaaaaaaaaaaaaaaa" E E "aaaaaaaaaaaa") ))
(assert (= (str.++  A A "aaaaaaaa")  (str.++  G "aaaaaaaaaaaaaaaaaaaaa" E "aaaaa") ))
(assert (= (str.++  B "aaaaaaaaa" A "aaaaaaaa")  (str.++  G "aaaaaaaaaaaaaaaaaaaaa" E "aaaaa") ))
(assert (= (str.++  D "aaaaaaaaa" B E "aaaaa")  (str.++  G E E "aaaaa") ))
(assert (= (str.++  A D D)  (str.++  A "aaaaaaaaaaaaaaaaaaa" E "aaaaaaaaaaaa") ))
(assert (= (str.++  A A "aaaaaaaa")  (str.++  B "aaaaaaa" E E "aaaaaaaaaaaa") ))
(assert (= (str.++  A A "aaaaaaaa")  (str.++  "aaaaaaaaaaaaaaaaaaaaa" E B "aaaaaaaaaaaaaaaaaaa") ))
(assert (= (str.++  A B "aaaaaaaaaaaaaaaaa")  (str.++  E E "aaaaaaaaaaaaaaaaaaaaa" E "aaaaaaaaaaaa") ))
(assert (= (str.++  C "aaaaaaaaa" A "aaaaaaaa")  (str.++  F "aaaaaaaaaaaaaaaaaaaaaa" "") ))
(assert (= (str.++  A B "aaaaaaaaaaaaaaaaa")  (str.++  G E "aaaaaaaaaaaaaaaaaaaaaaaaaa") ))
(check-sat)
(get-model)
