Variables {BD}
Terminals {ab}
Equation: aaaDDDabbDabBDbabbaaDb = aaaDbDabbbabaDDDbabbabaDDDaaaDDaDbaabb
Equation: DDDaaaaaaaaaDDbDaabaaaaaaDDbDaaDababaD = DDbaaaaaaaaaDbDDaabaaaaaaDDbDaababaDab
Equation: aaaDaaDabbDaaDDaaDDDaDbaaDbaaDaDaaabab = aaaDaaDaDDDaaDDaaDbbaDDaabbaababaaabab
Equation: aaDDaDDDaDDaaaaaDbaabDDbabbbDaaaDbDbaa = aabDabDbabbaaaaaDDaabbDDaDbDbaaaDDbDaa
Equation: baaaDabababbaDaaabDbaaDbbaDaaDaaaDabDb = baaaDabaDabDabaaaDbbaabbbabaabaaababbD
Equation: DaabaabaabaDaababDDababDDbaabaDaDbbaDb = baaDaaDaaDaDaaDaDbbaDabbbDaababaDDbaDD
Equation: aDababDDaabbabbbbDbaaDbbbaaaaaDaDDaaba = abababbbaabbabbbDDbaaDbDDaaaaabaDDaaDa
Equation: DaababDDaaaabbbaaaaabDDababDaDaabDbaDb = DaabaDDDaaaabbbaaaaabbDababDabaaDDbaDD
Equation: baaaaDDaaaaDaDaaabDDbabaaDbDabaDaaaaaD = DaaaaDbaaaabaDaaabDbbabaaDbDababaaaaaD
Equation: bbaabaDbbaaDabaaaaDaaaababbaaDaDaDDaab = DbaababbDaababaaaaDaaaababDaaDabaDbaaD
SatGlucose(100)