Variables {BAC}
Terminals {ab}
Equation: aAaaa = aabbaabaaabCaaaaaababbaaa
Equation: CabbbabAbCCaabaabCaaaCbaaabbbbbaCCbaab = CabbbabbbbbaabbbbaCaabaabbaaaaCbaaaBabaCbaab
Equation: bbCbaabaaaCbCabCbbCabbbabCababbCaaabbbbCaCa = bbCCabaaababbaabbabbCabbCbbaababbbaaaabbbbCabaa
Equation: bbbCbbabaabbbbbaaabaaabbaaabbaaaCaaaaCbCCbbaabb = bbbbabCbaabbbbCaabaaabbaaabCaabaaaaaCbCbabbaabb
Equation: babbbbCbCbbabaabCbbbbaaCbaBbCaabaaaaCaabaa = CBabCbCbaabCbbbbaababaBbbaaabaaaabaaaCa
Equation: baCaCbaabCaaaaabaCaCabbCbCabbbabbCaCbbbbCb = babaabaCabCaaaaababaaCabbbabbaabbbabbCabaBab
Equation: aaaCbbCababaaaaaaaabCbaabbCBaabCbaaaaCbbbb = aaaCbbCabaCaaaaaaabCCabbbabbbbbaabCCaaaCbbbb
Equation: baCbbaCbaabaabCbbaabbbaaaabababbaaaaaabCaabbaaaa = baCbCCCaCabCbbaabbbaaaaCCbCaaaaabbaaabCaaa
Equation: bbCaabbaabCbCbaCbaaabaaabCaCbbbbaabbCaabbbaab = bbbaaabCabbabCCbabaaabaaabbaaCbbbCabbbaaabbbaab
Equation: baabbbbbbaCbaaaCaabCabCaCbbbbCabababCbabaaabb = CaBCCCaabaaabbaabbaababbbbbaabaCbCCCaabb
Equation: baaCabbababbbabbbaabbababCbaabbaabCaaCabbaabbbba = CabaabCCbbbabbCabbaCbbabaabCabbaaabaabCabbbba
Equation: bCabCaaaabaCbaaaaBaCCaabbCabaCbbCaaabbbb = bCabbaaaaaCbaCaaabbbbCbabaaabbCaCCbbCaaabbbb
Equation: aaCaCaabbbbabbCaaaaaaabCabaaaaaaaaCbaaaabbCbC = aabaabaaabbbbabbCaaaaaaabCaCaaaaaaaCbaaaabbCbC
Equation: aabbaaabaaaaaaaaaCCCbCabbaCabbaaaaCCaabbaabC = aabbaaaCaaaaaaaababababbaabCCabCaaabaCaabbaabC
Equation: aaaabaaaababCaaabbbabCabbbCaCaaCbCabaCbaababa = aaaaCaaababbaaaabbbabCabbbbaabaaababCaCCbaaCba
Equation: aaaabbCbbbabbaaCbCBbbaCaCCbaCabCaaCaaab = aaaabbCbbbabbaababCBbCbaaCbababaabCaaCaaab
Equation: abaaaabbaaaaabbbaabCaaaaabbbababaaaaaaaBbbbaaaa = abaaaabbaaaaabbCabCaaaaabbCCCaaaaaaBbbCaaa
SatGlucose(100)