Variables {A}
Terminals {ab}
Equation: baaababbbabaababbbbbaabababbaaaaababbababbbbbbaaababaaababaababbbbbaabba = baaababbbabaaAbba
Equation: bababaabbaabbbabbababaabaabbababbabbbaaaaaaabaabbabbbaaababbbaaababbabbb = bababAaaaaabaabbabbbaaababbbaaababbabbb
Equation: aaabaabbbaaabAbbbabbbbabaabbaaaabbbbaababbbababaabbbaabbbbb = aaabaabbbaaabAbbbabbbbabaabbaaaabbbbaababbbababaabbbaabbbbb
Equation: bbbbbbbaabaaabbbbabaaaaAbaaaabaaababbbbbabbbbbaaaaaaaaababa = bbbbbbbaabaaabbbbabaaaaAbaaaabaaababbbbbabbbbbaaaaaaaaababa
Equation: baaaaabaabbbbaababababaababbbbbbaaabaaabaaAbaabbaabbbaaabaa = baaaaabaabbbbaababababaababbbbbbaaabaaabaaabbbbaaaabaabbbaabbaabbbaaabaa
Equation: babaaabbbbabbbaaabbbbababaabbabbababaaaabbababaaaaaaabaAbaa = babaaabbbbabbbaaabbbbababaabbabbababaaaabbababaaaaaaabaabbbbaaaabaabbbaa
Equation: baabaabbbabbaAabaaaaaaabaabbbaabbbabba = baabaabbbabbaAabaaaaaaabaabbbaabbbabba
Equation: bbbAbabaa = bbbaaaababaaaabaabbbbbababaabbbbaaabababababbabbbaababaaaaababbaaabbabaa
Equation: abaababbbaabbabbbabbabAbabbbabbbabbaababbabababbaaaaaaabb = abaababbbaabbabbbabbabbbbaabbbababbbabbabbbabbbabbaababbabababbaaaaaaabb
Equation: baaAbbaaaabbAAAaAaaAaaaaabAaaaaabaAabbbabbaabaAbbbaaaaabaaabAbabaabaaaAb = baabbAaaaaAbAbAaAaabaaaaabbaaaaabababbAaAbaaAaAbAbaaaaabaaabAAaAaaAaaaAb
Equation: AbAAabaAabbaAbaabaaAaabAbaabAaAAbbbbaAAaaabbaaaAAaaaaAabaaaaabbbababaaba = bbAAaAaAabbaAAaabaabaaAbAaaAbaAbAbAbabAaaabAaaaAAaaaaAabaaaaaAAAaAaAaaba
Equation: aabaaAAaabaAaAbaAaAbbAaabaAAAAbaaAbaAbaAAaaabaabAaaaaaabaaaAaAaAAAaaAabb = aaAaabAaababaAAaAabAAbaaAabbAbbaabbabAaAAaaabaaAbaaaaaabaaabaAaAAbaaAabb
Equation: bbAabaAAbaaAAbAaabaAAaabaaaaaaaaabAbAbaaabaaAbaAAaaaaAaaAabAbaaAbbbAaaAb = AbbaAaAAAaaAbbbaababAaaAaaaaaaaaaAbbAAaaaAaaAAabbaaaaAaabaAbbaaAbbbbaabb
Equation: baAbaAAbaaAbaaabaAaaaaaAaAAababaAAaAaAaAabbaAbaaAbAaaAAbbaaaaAabaaaAaabb = babbabbAaaAAaaabaAaaaaabaAAaAaAabAababaAaAbabAaabAAaabbAbaaaabaAaaabaaAb
Equation: aaabAAabAbaabbAbbAaaaaaAAbaaaAaaaaabAbabaaabaAaabAaabbAabbbbabbaaaAAAaba = aaaAbAabAbaabAbbbAaaaaabAbaaaAaaaaabbAaAaaaAabaabAaabbbaAAbAaAbaaaAAAaba
Equation: baAbAbbAaAaaabAaaaaAaaAaAababaaabaAAaaabaaaabbabAaaAabaababaAAbaaAaababb = AabAbAbAaAaaaAAaaaaAaabaAabaAaaabaAAaaabaaaaAbabbaaAabaababaAbbaaAaababA
Equation: AaAAaAbAaAbaaAAabaAAabaAaaaabaaaaaaabbaaAabbaaaabaaaaaabaabAAaAaababaaaa = babAabbbaAbaabAababAaAabaaaabaaaaaaabbaababAaaaabaaaaaaAaabbAabaaAaAaaaa
Equation: baaaaAAaaAAaaaaAbaabaabAAbaaaaAbaaAaaabaAaaaabbbaaaaaAaaabbAabAabaaAAaaa = AaaaaAAaabAaaaaAbaabaaAbAbaaaaAbaaAaaababaaaaAbAaaaaabaaabAbaAAabaaAbaaa
Equation: bbAaaabaabAaAbaaAbaAaAbAAAbaaaabbAabAAbbAAaabAbaaAAaabbAaaaabAbbaAaAbaaA = bAbaaaAaabAabAaabAaAabbbAAAaaaaAbbaAbbbbbAaaAAAaaAbaabAAaaaabAAbabaAAaaA
Equation: ababbAAaAaAAAbbbaabAaAAbbAbAbAAaaAaaabbaAAAAbabAbaaAbbaaaAaaAbaAaAabaaAa = abaAbbbababbAbbbaabAabbAAAbAbbAaabaaabAaAbbbAaAbbaabAbaaabaaAAaAaAabaaAa
Equation: baaAaAaAAaAaaabaaabbAAAabaabAAaAAbbaaAaAabaaAaabbbaabAAaAAababaaaAaaaaaa = baaAaAaAbaAaaabaaaAAbbAaAaaAbAaAAbAaabaAaAaabaaAbAaabbAaAbaAaAaaabaaaaaa
Equation: abaAabaaababbaaaAaabaabAbaAabAAAbbAabaAbaaaaaabbaabAaaaAbaaabaaAaAAAAbaa = aAaAaAaaaAabAaaabaaAaabAAababbAAbAbabaAbaaaaaaAbaabAaaaAbaaaAaababbbAbaa
Equation: aabbaAabaaAAbAAaaaaAAabAabaabaaAAaaaababaAAaAaaaaaAbaAbabbaAabbaaAaaaaAb = aaAAabaAaaAbAAbaaaaAAaAbabaaAaabAaaaabababbabaaaaaAbabbaAAabaAbaabaaaabA
Equation: bbaaAabbaaaAaaAaaaaaaabbAaaabaaAaAaaAAaababAAAabaaAAaaaaabbaaAaaAaAbaaaA = AbaaAabbaaabaaAaaaaaaaAAAaaaAaabaAaabbaaAaAAbAabaabbaaaaabAaabaababAaaab
Equation: AbaaabaaaAabbbAaaaaabAaAaAaaaaabaAaAabAAAabbbbAaaaabbbaabbbaAbaabAbAaaAa = bAaaaAaaababAAAaaaaabbaAabaaaaababababbAbabAbbbaaaabbbaabAbaAbaaAAbAaaba
Equation: aAaaaAababaaaaAbaaabbabAAbbAAabbaAAabAaAAAabaAaaAaAaAbaaAaAaaaaaAbAbaaAb = abaaabaAaAaaaaAAaaabAaAAbbbAAabAaAbabbabbAababaababaAbaaAabaaaaaAAAAaabA
Equation: babAAbaaaaaAAaaaabaaaaaabbbAbabaaAabAbaAabbaAabaAaaAababAbAaAAaAaabbaAAb = babbbbaaaaabbaaaaAaaaaaabbbAbaAaaAabbAababbaAaAaAaaAabaAbAAaAbabaaAbaAAA
Equation: abaaaAaAAaaAAaaaAabaaaaaAaabAaAaaabAbAAAaaaAAAbaAbaabaaAbbaaaabbabaAabaa = abaaaAaAAaabAaaabaAaaaaaAaabbaAaaaAbAbbbaaabAbAabAaabaaAbbaaaabAaAaAaAaa
Equation: baaaababaabAAaabbAaaaAabaaaaababbAbAabbababbbAaababaAAbaaababAbaAbAaaaAb = baaaaAaAaabAbaabAAaaababaaaaababAbbbaAAabaAAbbaaAaAabAbaaaAabAbabAbaaabb
Equation: AAababAbAaaabbbaaaaaabaabAababAaaaAAaaaaabAAAabAAbAabaaAAAbAabaAAbaabaab = bAaAaAAAbaaaAAAaaaaaaAaaAAababAaaaAAaaaaabAbAabbbbbaAaabAAbAaAabbbaabaab
Equation: aaaabbAAbaaaaaAbAabaaAAbAaaAabbaAAbaabaAaaAAabbaAababaabbaAbAAaAbabAaAaa = aaaaAAAbbaaaaaAAAabaabbbbaaAaAAaAAAaababaabbabAaAaAaAaabAaAbbAabAaAAaAaa
Equation: bbbAaAbabaaabAAAaAabAAAaaAbAbaabaabbaaabbaaAaAbbabaAabaabaaabAaAbaAabAAa = AAbAaAAaAaaaAAAbaAaAbbbaaAbbAaaAaaAAaaaAbaaAabbAababaAaabaaaAbaAAababAba
Equation: bababAbAaaaaaAbaabaaaAbAAbbaAAAaAbbAAaababbbbababaAaAAAaAaaAAabaAAaAaAaa = AaAaAAbbaaaaabbaabaaaAAAbbAabAAabAbAbaaAaAAAAababababbAabaabbababAabaAaa
Equation: bababaaababaaAabaaabbaabAAbabbabaaaAaAaaAAbaAaaaaaababAababaabaAaaAAabAa = baAabaaababaaAaAaaaAAaaAAAbabAaAaaaAaAaabbAaAaaaaaabaAbabaAaaAabaabbaAba
SatGlucose(100)