Variables {BFAC}
Terminals {cabd}
Equation: aCbaabacAadd = aCbaaCacaacCccCbcBaaaCdadCdcFccaadCcaaadacCdddbdcbadd
Equation: ddacCCabbCcabCdccaadaCacCaaadaCccadaCccdddcbacCadddaCacdaCdbbCbbcada = ddacCCabCCcabCdccaadabacCaaadabccadabccdddcCacbadddaCacdabdCbCbbcada
Equation: bCaccddcdCdaacCdacacCdaaacCdbdCdCaccadaaaaaddCbcCCbadCdcccdcCdacdCcC = CbaccddcdCdaacbdacacCdaaacbdCdCdbaccadaaaaaddbbcCbbadbdcccdcCdacdCcC
Equation: CcdcdcadabaaabcaaddaccdcacdaccdabbdbCCabcbccdadbbdddddccaadbbccaddca = bcdcdcadaCaaaCcaaddaccdcacdaccdaCCdbCbabcbccdadCCdddddccaadCCccaddca
Equation: caCbCbaaddcadbcbddcCbCddaCdacbdbacCdaaaabdddbaCbddcCcacCabddcbaCbaCb = cabCbbaaddcadCcCddcbCCddabdacbdCacbdaaaabdddbaCCddcCcacbabddcCaCCabC
Equation: aaadCadCdCdadbcbaCddcabaCabdcCdcCadacadaCCdacccCaadCcCdCccdbacbacaaa = aaadCadCdbdadCcbabddcaCabaCdcbdcbadacadabCdacccCaadbcbdCccdbacCacaaa
SatGlucose(100)