(set-logic QF_S)
(declare-fun B () String)
(declare-fun A () String)
(declare-fun C () String)
(assert (= (str.++  "cceeefebcdaef" B "fdaacaddf")  (str.++  "cceeefebcdaefefabbfcc" C "beafdedcffdeacdbefbbfffaafdcfaedbeccbdddafdaacaddf") ))
(assert (= (str.++  "bfdcf" B "fdefacbefcdfb")  (str.++  "bfdcf" B "fdefacbefcdfb") ))
(assert (= (str.++  "ddabeefeaafbbeeefbcedddaaddaf" B "bdadddaaffeccebcafbacadedacbcdcebbffb")  (str.++  "ddabeefeaafbbeeefbcedddaadda" C "cfbbcaffabbdadddaaffeccebcafbacadedacbcdcebbffb") ))
(assert (= (str.++  "defaaedffccebbfdeadbeafcafbffcfbdfbbedfffbdbbbbcfdcceebbacabbebfeedfefcbfddadddf" "")  (str.++  "defaaedffccebbfdeadbea" C "ffcfbdfbbedfffbdbbbbcfdcceebbacabbebfeedfefcbfddadddf") ))
(assert (= (str.++  "adcdacfaefdefceeeceffdaccfabbbddbffbaabddebdbecdddc" C "dfceebbcaabdbbecdffbeced")  (str.++  "adcdacfaefdefceeeceffdaccfabbbddbffbaabddebdbecdddcfcafbdfceebbcaabdbbecdffbeced" "") ))
(assert (= (str.++  "eeaafaacbaeeaeebfeffaaeeefcebdbfffabddedddfecbfdbfcefabdaabbaeaaefc" C "fdedecdb")  (str.++  "eeaafaacbaeeaeebfeffaaeeefcebdbfffabddedddfecbfdbfcefabdaabbaeaaefcfcafbfdedecdb" "") ))
(assert (= (str.++  "ccfedcefdbddfcebbfeaecedffbfecdfddecabdffefcafbadfabfafabfffdfffdddeeabbdcabbdef" "")  (str.++  "ccfedcefdbddfcebbfeaecedffbfecdfddecabdffe" C "adfabfafabfffdfffdddeeabbdcabbdef") ))
(assert (= (str.++  "affaeeffdaccd" C "bcdbbdfadcfcabacabbfcdffbefaeefbaeefeffafbcfcfacebaabadddcdafc")  (str.++  "affaeeffdaccdfcafbbcdbbdfadcfcabacabbfcdffbefaeefbaeefeffafbcfcfacebaabadddcdafc" "") ))
(assert (= (str.++  "dcfecbcacebcdbfaffddeafacdeeddfaeeefdcabffacbbeabfacacbbebdb" C "fdcefecebebedde")  (str.++  "dcfecbcacebcdbfaffddeafacdeeddfaeeefdcabffacbbeabfacacbbebdbfcafbfdcefecebebedde" "") ))
(assert (= (str.++  "bbefeaabceaabf" C "eedfeceedeafdddaffffaceacacceababaccfcacdbaaeffaacbebdacfdfbb")  (str.++  "bbefeaabceaabffcafbeedfeceedeafdddaffffaceacacceababaccfcacdbaaeffaacbebdacfdfbb" "") ))
(assert (= (str.++  "debeeceafabedcbdbabddabf" A "deefffccfbfcbedbbbdbbedaddedebbacfbcfdefdeeb")  (str.++  "debeeceafabedcbdbabddabffecceeafaabadeefffccfbfcbedbbbdbbedaddedebbacfbcfdefdeeb" "") ))
(assert (= (str.++  "eaabadddecadfedfeafaabcceacdeeaabaeefcaaeedacbfcbdededeebeedbaafeabdebccbfcabfcd" "")  (str.++  "eaabadddecadfedf" B "bcceacdeeaabaeefcaaeedacbfcbdededeebeedbaafeabdebccbfcabfcd") ))
(assert (= (str.++  "beeffebfefdebfbcacaceaffeefefaee" B "bfbdcdeecbfefedceceadddcdeddfadbdbcfcbffcbb")  (str.++  "beeffebfefdebfbcacaceaffeefefaee" B "bfbdcdeecbfefedceceadddcdeddfadbdbcfcbffcbb") ))
(assert (= (str.++  "dcbfabbcdafbeb" B "fbedecabdfbefabbcfcdcfefaaddeeaceefafefddceadeefadecacbfaabdf")  (str.++  "dcbfabbcdafbebeafaafbedecabdfbefabbcfcdcfefaaddeeaceefafefddceadeefadecacbfaabdf" "") ))
(assert (= (str.++  "beccbdccfadaceddaaeefeecbcdccaaad" B "bffddfeebdeeccdffabdcbeccafaeaeefbefccdfcb")  (str.++  "beccbdccfadaceddaaeefeecbcdccaaadeafaabffddfeebdeeccdffabdcbeccafaeaeefbefccdfcb" "") ))
(assert (= (str.++  "bcebabbbeffbacbeac" B "eeffffcbdacdeddffafeceebacbadeecfbccdbeaeabaddeddbbcacfbd")  (str.++  "bcebabbbeffbacbeaceafaaeeffffcbdacdeddffafeceebacbadeecfbccdbeaeabaddeddbbcacfbd" "") ))
(assert (= (str.++  "cbbbceeaffbaedfdccdfbcebcebbccbeeafaadbbfffecfbfeafbffdbccbbaeacfcbbffacafcefccd" "")  (str.++  "cbbbceeaffbaedfdccdfbcebcebbccbe" B "dbbfffecfbfeafbffdbccbbaeacfcbbffacafcefccd") ))
(assert (= (str.++  "aaebafbadfaccddbcd" A "eabdb" B "eaaaadedcdef")  (str.++  "aaebafbadfaccddbc" C "fbeabdb" B "eaaaadedcdef") ))
(assert (= (str.++  "bcbeedbdabaecdcbfacacdbfebdafcabddcebfeeaddbdbaebdbeecdcbefcdfccdfaaaeccfcbebbfb" "")  (str.++  "bcbeedbdabaecdcbfacacdbfebdafcabddcebfeea" C "baebdbeecdcbefcdfccdfaaaeccfcbebbfb") ))
(assert (= (str.++  "ffaaacdcaadbecaafcbdeabfbffadabfdebaebbcfdbdf" C "cabbafeaadccceccddaffcdedcccccd")  (str.++  "ffaaacdcaadbecaafcbdeabfbffadabfdebaebbcfdbdf" C "cabbafeaadccceccddaffcdedcccccd") ))
(assert (= (str.++  "aeeedccaebccbadfadfececadbddbeacffdebdfedccacdfbffeeedffbadedfddecdf" C "feaadffd")  (str.++  "aeeedccaebccbadfadfececadbddbeacffdebdfedccacdfbffeeedffbadedfddecdf" C "feaadffd") ))
(assert (= (str.++  "cadcbfcdabffffbcccdbdfbdceccbddcbddadbfbefedebabdcbadffccbfebfbfbbddcabaedefabdf" "")  (str.++  "cadcbfcdabffffbccc" A "dceccbddcbddadbfbefedebabdcbadffccbfebfbfbbddcabaedefabdf") ))
(assert (= (str.++  "bd" C "badddcbdbccdefbdedfcefbbeefeebedbbbbefdfeeabffaafdcaaafafedecfeedffecdaeee")  (str.++  "bdddbdbadddcbdbccdefbdedfcefbbeefeebedbbbbefdfeeabffaafdcaaafafedecfeedffecdaeee" "") ))
(assert (= (str.++  "bdbaadccaaadeaefbbcbafababbadfef" C "bfbbbbfcdffccadcfdcaebedfebfadfedcbdadeacccd")  (str.++  "bdbaadccaaadeaefbbcbafababbadfefddbdbfbbbbfcdffccadcfdcaebedfebfadfedcbdadeacccd" "") ))
(assert (= (str.++  "dcaebebbfbfdddefbbfbcccaceacdedaddafeabadcbccddacccccdfadfdbcddabeaeedceed" C "ef")  (str.++  "dcaebebbfbfdddefbbfbcccaceacdedaddafeabadcbccddacccccdfadfdbcddabeaeedceed" C "ef") ))
(assert (= (str.++  "cedbeadfefffcb" C "cbcaafeeedbedaabddeabccccececbfedfcfebaefcbbaddabcffedaacafbea")  (str.++  "cedbeadfefffcbddbdcbcaafeeedbedaabddeabccccececbfedfcfebaefcbbaddabcffedaacafbea" "") ))
(assert (= (str.++  "afdcbdebcebfccfbaacadfbebabfdccdaadfda" C "a" C "aecbceeedfcfbccabfcffffadcfaffcbd")  (str.++  "afdcbdebcebfccfbaacadfbebabfdccdaadfdaddbdaddbdaecbceeedfcfbccabfcffffadcfaffcbd" "") ))
(assert (= (str.++  "dddbdeaedefaadafeddccdeeaedacbfbafbfccfbceefbafafabdafacacbecdbdcafeccaceabaacda" "")  (str.++  "d" C "eaedefaadafeddccdeeaedacbfbafbfccfbceefbafafabdafacacbecdbdcafeccaceabaacda") ))
(assert (= (str.++  "cbeadfddeaddacaccaedbfcaabbcdcadacfeabaeddcabbdedafaf" C "aadaaacccdfefacdbfcacef")  (str.++  "cbeadfddeaddacaccaedbfcaabbcdcadacfeabaeddcabbdedafaf" C "aadaaacccdfefacdbfcacef") ))
(assert (= (str.++  "dbcacebacedbcafcaddcafeeeffecacfaaceedfcfedfbbdf" C "ddbcffbaccdeabbdeaaeaaedfdff")  (str.++  "dbcacebacedbcafcaddcafeeeffecacfaaceedfcfedfbbdfddbdddbcffbaccdeabbdeaaeaaedfdff" "") ))
(assert (= (str.++  "dfeddedbbfaeecaabddeedaceaab" C "dbcefbfdeaecdfddddccadfcfbffdccedaeedeaacdddffbc")  (str.++  "dfeddedbbfaeecaabddeedaceaabddbddbcefbfdeaecdfddddccadfcfbffdccedaeedeaacdddffbc" "") ))
(check-sat)
(get-model)
