Variables {BDA}
Terminals {cab}
Equation: babcacbbccbaabbbaabbDabaab = babcacbbccbaAbcbcacaaaaccbaabaaabbabaab
Equation: babaababaabaaacaaacacbbbbBcabbaacbcabbccacaccaab = babaababaabaaacaaacacbbbbBcabbaacbcabbccacaccaab
Equation: aaccbcbababcbabaaacbbbbcbacccbcacabbaaabcccccabbaabcba = aaccbcbababcbabaaacbbbbcbBcabbaaabcccccabbaabcba
Equation: abbccaabccacbcaabbbcabaaaacbcccaacccbcaabbbabbbccbcbba = abbccaabccacbcaabbbcabaaaacbcccaBabbbabbbccbcbba
Equation: aabbccbaabcaabbBcbbcbabcbbcbbcbcbabbccbabbbbbcbc = aabbccbaabcaabbacccbcacbbcbabcbbcbbcbcbabbccbabbbbbcbc
Equation: cbBbacabcbacabccbcabbbbabcaaabcabaaaacbaabaabaca = cbBbacabcbacabccbcabbbbabcaaabcabaaaacbaabaabaca
Equation: bcbcbbBacacbcbaabcbcbbabababbcbabbbccabccabbcbab = bcbcbbBacacbcbaabcbcbbabababbcbabbbccabccabbcbab
Equation: ccbcacbbacccbcaaabbacbaacaacbbcabbacaaaaaababcabbccbac = ccbcacbbBaabbacbaacaacbbcabbacaaaaaababcabbccbac
Equation: bbbaccaacbacabcaaabacaaaaacacaabccaacabbcaacccbcabbccc = bbbaccaacbacabcaaabacaaaaacacaabccaacabbcaBbbccc
Equation: bccacccbcaabccacaaacabaacaccaaacbbaabbccabaccccabbbbac = bccBabccacaaacabaacaccaaacbbaabbccabaccccabbbbac
SatGlucose(100)