(set-logic QF_S)
(declare-fun B () String)
(declare-fun D () String)
(declare-fun E () String)
(declare-fun A () String)
(assert (= (str.++  D D D "a" A A A E B D D A "aa")  (str.++  D A A "aaaaa" A "a" A A "aaaaa" A A "a" A "aaa" A D D "a" A A A "aa" A "a" D "aa" A A D "a" A "aaa") ))
(check-sat)
(get-model)
