(set-logic QF_S)
(declare-fun B () String)
(declare-fun A () String)
(assert (= (str.++  "a" B "ccbaaabbcabbacccbabaa")  (str.++  "aabbaabaababccacbcbcabaabccbbccbbcc" A "baaabbcabbacccbabaa") ))
(assert (= (str.++  "acacbbccccabbcabcaaabaabaabaabbcccbcbaaacacccabbbbbbabcabcbcbababbaabbcbaacaabcaabb" "")  (str.++  "acacbbccccabbcabcaaabaabaabaabbcccb" A "bb") ))
(assert (= (str.++  "b" B "ccbabacaaccccbbababaaabbaaaccabbaababacbababcacbbbbcb")  (str.++  "b" B "ccbabacaaccccbbababaaabbaaaccabbaababacbababcacbbbbcb") ))
(assert (= (str.++  "baaccbccbccacbacbb" B "aababaabcbcbaaacbcbcbacbbcaacaccbbbcababcacabbbab")  (str.++  "baaccbccbccacbacbbcaccbacaacbba" A "abcbcbaaacbcbcbacbbcaacaccbbbcababcacabbbab") ))
(assert (= (str.++  "cabcabaacccbccabccaababaababcbccaaacbcbbaabbccbcbcbacabcbbccaccabaacccabbabcabbccbb" "")  (str.++  "cabcabaacccbcca" A "ababcbccaaacbcbbaabbccbcbcbacabcbbccaccabaacccabbabcabbccbb") ))
(assert (= (str.++  "bbbabacaaacbabbbbaaabcacbcabcacaa" B "acacacc")  (str.++  "bbbabacaaacbabbbbaaabcacbcabcacaa" B "acacacc") ))
(assert (= (str.++  "bbcbabbbcccaaccccb" B "cbaaacacabcaaabaacbaccbababcaabb")  (str.++  "bbcbabbbcccaaccccb" B "cbaaacacabcaaabaacbaccbababcaabb") ))
(assert (= (str.++  "a" B "bbacbaabaaccacccbbcbbabccbbbabcaccaccaccccabbccacccaabcbababbb")  (str.++  "aaccacabccccabcbcb" A "bccbbbabcaccaccaccccabbccacccaabcbababbb") ))
(assert (= (str.++  "cccbbbccbbaccbb" B "abccaacbc" A "bbaacaa")  (str.++  "cccbbbccbbaccbbabbccaacabbbaccbabbcbbabaaabcbcaaabaabcbbbbccabacabccaacbcabbbbaacaa" "") ))
(assert (= (str.++  "cccbccbbcaabccacabbcccccbabbbccababbbccabbbcacabbabcbabcaaccacacbaabbabbbaaccbaacac" "")  (str.++  "cccbccbbcaabccac" A "cccccb" A "bccab" A "bccabbbcac" A "abcbabcaaccacacbaabb" A "baaccbaacac") ))
(assert (= (str.++  "aaabbacaaba" A "abbaacccbbccacacaaccbbaaaacccbbbaccbbaccccacabcbaaccacbccbacabbccaaab")  (str.++  "aa" A "acaabaabb" A "aacccbbccacacaaccbbaaaacccbbbaccbbaccccacabcbaaccacbccbac" A "ccaaab") ))
(assert (= (str.++  "cababaaaaaaaaba" A "acababccbbcbaccbbccacbbaabccacabaabcccaaabcccccacbbbcbbbcbccacccb")  (str.++  "cababaaaaaaaaba" A "acababccbbcbaccbbccacbbaabccacabaabcccaaabcccccacbbbcbbbcbccacccb") ))
(assert (= (str.++  "cacacacbabccbbcbcaab" A "bcaaccccbccacabcaaccabbbaaabbcacb" A "acbcacbcaabbbbccaabaaaca")  (str.++  "cacacacbabccbbcbcaab" A "bcaaccccbccacabcaacc" A "baa" A "cacb" A "acbcacbca" A "bbccaabaaaca") ))
(assert (= (str.++  "bcacacbaabaabbacacaccbbbcaacabbccaabccabccbccbaaaaacbaccacacbabaaabcbcbbbbabbababba" "")  (str.++  "bcacacbaaba" A "acacaccbbbcaacabbccaabccabccbccbaaaaacbaccacacbabaaabcbcbbbbabbab" A "a") ))
(assert (= (str.++  "acbbbbabbcccaccbabaccaccabcacbbcaacbccbcbbcbacabacbbcbaacbcbaaabaababcaacacbcbabaab" "")  (str.++  "acbbbb" A "cccaccbabaccaccabcacbbcaacbccbcbbcbacabacbbcbaacbcbaaabaababcaacacbcbabaab") ))
(assert (= (str.++  "acaa" A "babbccaaaabaababaaacaaaaacbcaccccbacbbbaaababcac" A "c" A "acbbbb" A "abaaacababcb")  (str.++  "acaa" A "babbccaaaabaababaaacaaaaacbcaccccbacbbbaaababcacabbc" A "acbbbbabbabaaacababcb") ))
(assert (= (str.++  "abac" A "aaabcabaccbccacaaabcbcabcacacacbbbabcbbcbbaaaaaabacbaccbacbbbacbcbbbcccacbac")  (str.++  "abac" A "aaabcabaccbccacaaabcbcabcacacacbbbabcbbcbbaaaaaabacbaccbacbbbacbcbbbcccacbac") ))
(assert (= (str.++  "baaaccaababaabcaccacbbbaaccccccccccacbacbcccccbaccbcbaabccbacabaaccccabaaaaaabbabac" "")  (str.++  "baaaccaababaabcaccacbbbaaccccccccccacbacbcccccbaccbcbaabccbacabaaccccabaaaaa" A "abac") ))
(assert (= (str.++  "ccccccabacaccaccbacbbc" A "bbcbccbbcbbcbba" A "bcaccbcccaaaccaabbbbbababcbabbcbabccbbcc")  (str.++  "ccccccabacaccaccbacbbc" A "bbcbccbbcbbcbbaabbbcaccbcccaaaccaabbbbbababcb" A "cbabccbbcc") ))
(assert (= (str.++  "cccbcccacbcababbbccbacccbbaccbbbcaacaaabbbbaaaacababcbaabcaacbcb" A "ccaaaacbaccaccaa")  (str.++  "cccbcccacbcab" A "bccbacccbbaccbbbcaacaaabbbbaaaacababcbaabcaacbcbabbccaaaacbaccaccaa") ))
(assert (= (str.++  "abbbabcabaabbcaacbbbaacbcacbabaacbbbac" A "cbaabbabaacabccaba" A "caccbcb" A "accbabcbaab")  (str.++  "abbbabcabaabbcaacbbbaacbcacbabaacbbbacabbcba" A "abaacabccaba" A "caccbcb" A "accbabcbaab") ))
(assert (= (str.++  "caaccacaabcbabababccba" A "cca" A "bcabaaabcbbcccbbbbabbabcacabacbcabab" A "bcbb" A "bcbaca")  (str.++  "caaccacaabcbabababccba" A "ccaabbbcabaaabcbbcccbbbb" A "abcacabacbcabababbbcbbabbbcbaca") ))
(assert (= (str.++  "accbcbcaaabcacccbaaabccbcbbccbcbcbbcbbcabaaacccabbbbabcacababcabcaabbaababacbbbcbca" "")  (str.++  "accbcbcaaabcacccbaaabccbcbbccbcbcbbcbbcabaaacccabbbbabcacababcabca" A "aababacbbbcbca") ))
(assert (= (str.++  "bcaabcabcccbbcacccaaacbbccbaaaacacacaabbbccbcbcabcabcbaabccabcbbabacccb" A "aaccacacb")  (str.++  "bcaabcabcccbbcacccaaacbbccbaaaacacaca" A "bccbcbcabcabcbaabccabcbbabacccb" A "aaccacacb") ))
(assert (= (str.++  "babaccacabcaaacbbaaacbbaaaccccabcbccacccbacabcbacccbcaaaa" A "bbbaccccacbcbbcacbaaaba")  (str.++  "babaccacabcaaacbbaaacbbaaaccccabcbccacccbacabcbacccbcaaaa" A "bbbaccccacbcbbcacbaaaba") ))
(assert (= (str.++  "c" A "abaaaaaaccbcccccbcccababcccbacaabaabcabbbaac" A "bcacbcbabcccaabcbbacbcabaacbcacb")  (str.++  "cabbabaaaaaaccbcccccbcccababcccbacaabaabcabbbaacabbbcacbcbabcccaabcbbacbcabaacbcacb" "") ))
(assert (= (str.++  "accabccca" A "baaaababaaaabcbcacbbcacaababcbabcbab" A "cbbccabacaaccbababcbcbcbaaacbcbc")  (str.++  "accabcccaabbbaaaababaaaabcbcacbbcacaababcbabcbab" A "cbbccabacaaccbababcbcbcbaaacbcbc") ))
(assert (= (str.++  "abbaaaabccacbabcabacbbabccababcabacabcabcbbcccaabbaccaacb" A "caabcbaabaabaccaabaaabc")  (str.++  A "aaaabccacbabcabacbbabccababcabacabcabcbbcccaabbaccaacb" A "caabcbaabaabaccaabaaabc") ))
(assert (= (str.++  "bacc" A "acaaabacbccaccaaaacabbbccbbabccbbccccccabccbccaaabcbabaaccabcbccaccaacbaaaab")  (str.++  "baccabbacaaabacbccaccaaaac" A "bccbbabccbbccccccabccbccaaabcbabaaccabcbccaccaacbaaaab") ))
(assert (= (str.++  "bcabaacb" A "bccaa" A "cacabaaccbbaacccaacccccacaabccbaccaacaaacaccbcccbacacaccbabbcbcb")  (str.++  "bcabaacbabbbccaa" A "cacabaaccbbaacccaacccccacaabccbaccaacaaacaccbcccbacacaccbabbcbcb") ))
(assert (= (str.++  "aacbcabaca" A "cbcccbbaccabcbcacaaaccccccaaabccabaacccbcabcbcbbacacccbbaaacababccbcab")  (str.++  "aacbcabacaabbcbcccbbaccabcbcacaaaccccccaaabccabaacccbcabcbcbbacacccbbaaacababccbcab" "") ))
(assert (= (str.++  "cbbabbbcbcc" A "cabbcbacabccacbabcabcbaacbcababbccccbcbaacacbbccbbbaaccbabaaacaccaacc")  (str.++  "cbb" A "bcbcc" A "cabbcbacabccacbabcabcbaacbcab" A "ccccbcbaacacbbccbbbaaccbabaaacaccaacc") ))
(check-sat)
(get-model)
