Variables {A}
Terminals {cabd}
Equation: dcadcacbabdaAaaAadbAabcbAadaaAbadaaddAdAcabdbccd = dcadAacbabdaAaacadbAabcbAadaacbadaaddAdAcabdbAAd
Equation: adbabddddacdaabAadaacbAaAbaAabdAddcbbdcddaabbcca = adbabddddaAdaabcadaaAbAaAbaAabdAddAbbdcddaabbcca
Equation: dddadcAbdccbacacaacbdabAbcAbaddcdcadaAddabaadacd = dddadAAbdccbacaAaaAbdabcbAcbaddcdcadaAddabaadaAd
Equation: AAddbcdbdbaaAbaccaddbbbcbacAdcaaabaaadacdabcbaAd = AcddbcdbdbaacbaAAaddbbbAbaAcdcaaabaaadaAdabAbacd
Equation: bbcAaadadbdcddcAadAbbbaAbcabaadbdbabcbbdbAAcacab = bbAcaadadbdcddAcadcbbbacbAabaadbdbabcbbdbccAacab
Equation: dccbaAdAbdddbaddabbdbdAacabbAacaAdabaddacadadAaA = dAcbacdcbdddbaddabbdbdcaAabbcaAacdabaddaAadadcaA
Equation: abbacbcdbdAAAAcbbbdaacabAaadccaAAddcAacddcddabdb = abbaAbAdbdAccccbbbdaaAabcaadcAaccddcAacddcddabdb
Equation: AabadabbadAAaadaadbbbAadabcaaAbbAbbddaccdbcabbda = AabadabbadccaadaadbbbAadabcaacbbcbbddaAAdbcabbda
SatGlucose(100)