(set-logic QF_S)
(declare-fun F () String)
(declare-fun E () String)
(declare-fun C () String)
(declare-fun D () String)
(assert (= (str.++  "bdaddbcacaec" E "adbeeadaae")  (str.++  "bdaddbcacaeccceddceddecd" C "eadaae") ))
(assert (= (str.++  "eabeebaeebbbbedcb" F)  (str.++  "e" C "baddaac") ))
(assert (= (str.++  "edaedaadcacdcba" D "edeeb")  (str.++  "edaedaadcacdcba" D "edeeb") ))
(assert (= (str.++  "dbaeddeddcbbbbecaaeabcedaeaaecdeaece" E "baeeecdaccd")  (str.++  "dbaeddeddcbbbbecaaeabcedaeaaecdeaeceaccbaeeecdaccd" "") ))
(assert (= (str.++  "ddebbaecaabeedaacabcdebebbaccea" E "decbdccacecedbde")  (str.++  "ddebbaecaabeedaacabcdebebb" E "eaaccdecbdccacecedbde") ))
(assert (= (str.++  "ebbcdcbdcaadbaa" E "cccbacbabbadedcbbeddacddbbecddec")  (str.++  "ebbcdcbdcaadbaa" E "cccbacbabbadedcbbeddacddbbecddec") ))
(assert (= (str.++  "deedaacaaebddbbaceebcceacbedccdecbbeecdbeaaccddbcc" "")  (str.++  "deedaacaaebddbbaceebcceacbedccdecbbeecdbea" E "ddbcc") ))
(assert (= (str.++  "dcbbdbaeaddbecbeacedabcdecddebccbddbcdabeebdc" E "ba")  (str.++  "dcbbdbaeaddbecbeacedabcdecddebccbddbcdabeebdc" E "ba") ))
(assert (= (str.++  "aedccabccaeaaecc" E "abedabcccbdbcebbbadcaecdbccdcdd")  (str.++  "aedccabccaeaaecc" E "abedabcccbdbcebbbadcaecdbccdcdd") ))
(assert (= (str.++  "cbbbbbddbbecbaebdcedbdbabcdcc" E "dcabdabaeaacaadaca")  (str.++  "cbbbbbddbbecbaebdcedbdbabcdccaccdcabdabaeaacaadaca" "") ))
(assert (= (str.++  "bdcaedaebeedbcaecdecabbccaadccbdccbbcaa" E "eaedaabd")  (str.++  "bdcaedaebeedbcaecdecabbccaadccbdccbbcaa" E "eaedaabd") ))
(assert (= (str.++  "acceccccaebaeeeabcaebceaedaadabbababbacabcbeceaeac" "")  (str.++  E "eccccaebaeeeabcaebceaedaadabbababbacabcbeceaeac" "") ))
(assert (= (str.++  "cabcceceaec" E "baddacebbecddadddeaedddedeababcedcdc")  (str.++  "cabcceceaecaccbaddacebbecddadddeaedddedeababcedcdc" "") ))
(assert (= (str.++  "accbbdbddebbecdbddacbacecddedcbceebcbccbecdebaadbe" "")  (str.++  E "bbdbddebbecdbddacbacecddedcbceebcbccbecdebaadbe" "") ))
(assert (= (str.++  "aebedbadbacebcabaccedddeabdbdcbceabccadedcbeeddeec" "")  (str.++  "aebedbadbacebcab" E "edddeabdbdcbceabccadedcbeeddeec") ))
(assert (= (str.++  "ceaebedeeeaebccbbeaaecadeeabac" E "ebddeceeebababddd")  (str.++  "ceaebedeeeaebccbbeaaecadeeabacaccebddeceeebababddd" "") ))
(assert (= (str.++  "aedbcececbbccaaadcbabddabacdadaebdcdeccbbbdbebc" E)  (str.++  "aedbcececbbccaaadcbabddabacdadaebdcdeccbbbdbebc" E) ))
(assert (= (str.++  "ed" E "ccbbabdbaddebacbaeabacecaecaeeebadbebabeddedd")  (str.++  "edaccccbbabdbaddebacbaeabacecaecaeeebadbebabeddedd" "") ))
(assert (= (str.++  E "adab" E "dccbedbdaaaeccdacccdeddbabdadadabaedeedc")  (str.++  E "adab" E "dccbedbdaaaeccd" E "cdeddbabdadadabaedeedc") ))
(assert (= (str.++  "ddeecccacecaadeeebcaabbcdacceacaaaeceeeedadeedacbc" "")  (str.++  "ddeecccacecaadeeebcaabbcd" E "eacaaaeceeeedadeedacbc") ))
(assert (= (str.++  "deeaaccaddadbcdabadeebacdcbdedadaeecacdbcdadbaeaad" "")  (str.++  "deea" E "addadbcdabadeebacdcbdedadaeecacdbcdadbaeaad") ))
(assert (= (str.++  "dcbecaaabecdab" E "becaababdaeaabdeabdeccdcbeddbaaeb")  (str.++  "dcbecaaabecdabaccbecaababdaeaabdeabdeccdcbeddbaaeb" "") ))
(assert (= (str.++  "babadecdcaabdad" E "aebcbabddaceacccedecaaaecdcbaecd")  (str.++  "babadecdcaabdadaccaebcbabddace" E "cedecaaaecdcbaecd") ))
(assert (= (str.++  "eaccccbbcaeceeecedececbebcaddebcedbeacdbebcdcabedb" "")  (str.++  "e" E "ccbbcaeceeecedececbebcaddebcedbeacdbebcdcabedb") ))
(assert (= (str.++  "dcdbabeebdedbeaeaedadaadaedebdbbdbdbabeaaeccbbb" E)  (str.++  "dcdbabeebdedbeaeaedadaadaedebdbbdbdbabeaaeccbbb" E) ))
(assert (= (str.++  "dbbdcddddcecdcaccabdeedddeeeacbcccbcdeebacaaedbbdb" "")  (str.++  "dbbdcddddcecdc" E "abdeedddeeeacbcccbcdeebacaaedbbdb") ))
(assert (= (str.++  "dcbbbadeacbceccbabaaacbbeeaccabdebbbcedacebbcccdec" "")  (str.++  "dcbbbadeacbceccbabaaacbbee" E "abdebbbcedacebbcccdec") ))
(assert (= (str.++  "eedacbeddcdc" E "ecaacdceadcebbdeebeceeaa" E "dadbdecb")  (str.++  "eedacbeddcdc" E "ecaacdceadcebbdeebeceeaaaccdadbdecb") ))
(assert (= (str.++  "edecadcbcbcdaebbd" E "acbebcecccdaedaceeadaaebadeccb")  (str.++  "edecadcbcbcdaebbd" E "acbebcecccdaedaceeadaaebadeccb") ))
(assert (= (str.++  "ed" E "abdccbbbaacacebacdddcbdaaabeabdccdbaacececaee")  (str.++  "ed" E "abdccbbbaacacebacdddcbdaaabeabdccdbaacececaee") ))
(assert (= (str.++  "bebdcaedbdcebeecacceadcadabaaecbdececedbcdeb" E "dee")  (str.++  "bebdcaedbdcebeec" E "eadcadabaaecbdececedbcdeb" E "dee") ))
(assert (= (str.++  "aecebbebbaedabcbccbcbbdccacccdccecdcbbbcdadeaccbad" "")  (str.++  "aecebbebbaedabcbccbcbbdcc" E "cdccecdcbbbcdadeaccbad") ))
(assert (= (str.++  "bbcbeacdcecaeddb" E "cdcdcecebeccccdceebabaaeabedcbc")  (str.++  "bbcbeacdcecaeddbacccdcdcecebeccccdceebabaaeabedcbc" "") ))
(assert (= (str.++  "cceacadeaacebaabcbbabdaabcbbccbbdbcbeb" E "dedeabdcd")  (str.++  "cceacadeaacebaabcbbabdaabcbbccbbdbcbeb" E "dedeabdcd") ))
(assert (= (str.++  "acecdcbcd" E "eeecbaedddbbabadebecacdacbbe" E "acebdad")  (str.++  "acecdcbcdacceeecbaedddbbabadebecacdacbbe" E "acebdad") ))
(assert (= (str.++  "baedaad" E "bcbdabdddaebadedbebadebebdeebcabcdccdebc")  (str.++  "baedaad" E "bcbdabdddaebadedbebadebebdeebcabcdccdebc") ))
(assert (= (str.++  "acdaddacabdeebacadebbbabecabbbddbccdcaab" E "dabcdcb")  (str.++  "acdaddacabdeebacadebbbabecabbbddbccdcaabaccdabcdcb" "") ))
(assert (= (str.++  "ebeacdcedccccddadbeeabccacb" E "bcbccceeadbcaeadacce")  (str.++  "ebeacdcedccccddadbeeabccacb" E "bcbccceeadbcaead" E "e") ))
(assert (= (str.++  "addbacccbcdbcdedbabeaacbbdbcdcecabbebddcbcdeaececb" "")  (str.++  "addb" E "cbcdbcdedbabeaacbbdbcdcecabbebddcbcdeaececb") ))
(assert (= (str.++  "aedcedeccacaabcabaceceabbabbaaaadbebabbbdddcdcacca" "")  (str.++  "aedcedeccacaabcabaceceabbabbaaaadbebabbbdddcdc" E "a") ))
(assert (= (str.++  "dedaadceb" E "bdcaabcdbdaeacecdcabaaaaeaedeaebbcddee")  (str.++  "dedaadceb" E "bdcaabcdbdaeacecdcabaaaaeaedeaebbcddee") ))
(assert (= (str.++  "aaceadacdbab" E "cccbabeadbadaaacdbedcdecdd" E "bbadbd")  (str.++  "aaceadacdbabacccccbabeadbadaaacdbedcdecdd" E "bbadbd") ))
(assert (= (str.++  "bedeadabccebedbdddeebdaa" E "ceabaeacabdeecceeaaccde")  (str.++  "bedeadabccebedbdddeebdaa" E "ceabaeacabdeecceea" E "de") ))
(assert (= (str.++  "eecabdabadcdbcbbbddbbdaaaeadccbcabb" E "bbcbdaddabee")  (str.++  "eecabdabadcdbcbbbddbbdaaaeadccbcabbaccbbcbdaddabee" "") ))
(assert (= (str.++  "dbcedaebcaabdbdeeecbaaaaccabdabaabaedcebddaecedccd" "")  (str.++  "dbcedaebcaabdbdeeecbaaa" E "abdabaabaedcebddaecedccd") ))
(assert (= (str.++  "daabbbdcbccaecaaccaebbaaecccdcaeadceaccacddcccddcb" "")  (str.++  "daabbbdcbccaeca" E "aebbaaecccdcaeadceaccacddcccddcb") ))
(assert (= (str.++  "debcbaaaeaae" E "ccadceccbdcccbcabdaabcedbbdabebd" E)  (str.++  "debcbaaaeaae" E "ccadceccbdcccbcabdaabcedbbdabebdacc") ))
(assert (= (str.++  "bedbeadceabeabbdacdeeddbccdacdecaea" E "eabddcdccecb")  (str.++  "bedbeadceabeabbdacdeeddbccdacdecaea" E "eabddcdccecb") ))
(assert (= (str.++  "acbcecdbdcdedcccad" E "dddedbdecdbabbbcbebadbbceedcc")  (str.++  "acbcecdbdcdedcccad" E "dddedbdecdbabbbcbebadbbceedcc") ))
(assert (= (str.++  "eadacdecebcebabdaabddeecbeeebccd" E "dcecddadcbdbeac")  (str.++  "eadacdecebcebabdaabddeecbeeebccd" E "dcecddadcbdbeac") ))
(assert (= (str.++  "aababcacbbbbdeddcaedddeabdceaedcaedddeaccebaccaabe" "")  (str.++  "aababcacbbbbdeddcaedddeabdceaedcaeddde" E "ebaccaabe") ))
(assert (= (str.++  "abbbcbeeadcecacbabbeabdecee" E "caeaecabbbebbceaaedc")  (str.++  "abbbcbeeadcecacbabbeabdecee" E "caeaecabbbebbceaaedc") ))
(assert (= (str.++  "bedbabbbecdaedebbabeaccbabdedcbedddcbaadcbaaebcaee" "")  (str.++  "bedbabbbecdaedebbabe" E "babdedcbedddcbaadcbaaebcaee") ))
(assert (= (str.++  "deeddeecacaaccabcccddeeecbebadaddecbdadbaedabebacd" "")  (str.++  "deeddeecaca" E "abcccddeeecbebadaddecbdadbaedabebacd") ))
(assert (= (str.++  "eddbcaaecadcebc" E "baddadbabccccdbbeaacbbdcbadedcca")  (str.++  "eddbcaaecadcebc" E "baddadbabccccdbbeaacbbdcbadedcca") ))
(assert (= (str.++  "ccdcddbbadaebdbdcbeeadaedabaeebdc" E "bbcddcdadbbcbb")  (str.++  "ccdcddbbadaebdbdcbeeadaedabaeebdc" E "bbcddcdadbbcbb") ))
(assert (= (str.++  "ccbdd" E "acbbceebeaeceaebbbeaebcdddcaadeebccbbdddec")  (str.++  "ccbddaccacbbceebeaeceaebbbeaebcdddcaadeebccbbdddec" "") ))
(assert (= (str.++  "edadccbccbecdbdaabeadabceccaeaeacebbbeeeeebbbbb" E)  (str.++  "edadccbccbecdbdaabeadabceccaeaeacebbbeeeeebbbbbacc" "") ))
(assert (= (str.++  "cbdabbadabedbeabdbecbebcdcdeedcebcdaabdacbc" E "eaae")  (str.++  "cbdabbadabedbeabdbecbebcdcdeedcebcdaabdacbcacceaae" "") ))
(assert (= (str.++  "bcedaadc" E "ccbdbbccaceaadadcabbeaaadbedeceabbbdedd")  (str.++  "bcedaadc" E "ccbdbbccaceaadadcabbeaaadbedeceabbbdedd") ))
(assert (= (str.++  "cbcbdeeaadbaaeddbdaaccebb" E "ecbbcbeaabbbcadaceadac")  (str.++  "cbcbdeeaadbaaeddbdaaccebb" E "ecbbcbeaabbbcadaceadac") ))
(assert (= (str.++  "bbcaeaeadcddbcbedabdecba" E "bcadeecbeadbeadebbbbcde")  (str.++  "bbcaeaeadcddbcbedabdecbaaccbcadeecbeadbeadebbbbcde" "") ))
(check-sat)
(get-model)
