(set-logic QF_S)
(declare-fun I () String)
(declare-fun K () String)
(declare-fun H () String)
(declare-fun G () String)
(declare-fun F () String)
(declare-fun J () String)
(assert (= (str.++  F "a" F "b" G I "b" K)  (str.++  "a" G G H H "b" J J "baa") ))
(check-sat)
(get-model)
