(set-logic QF_S)
(declare-fun H () String)
(declare-fun K () String)
(declare-fun F () String)
(declare-fun G () String)
(declare-fun J () String)
(declare-fun L () String)
(declare-fun M () String)
(assert (= (str.++  F "aaa" F "aaba" H H H "ba" K "b" M)  (str.++  "a" G "aa" H "a" J H "a" J "ba" L "a" L "baabaa") ))
(check-sat)
(get-model)
