(set-logic QF_S)
(declare-fun H () String)
(declare-fun I () String)
(declare-fun G () String)
(declare-fun F () String)
(declare-fun J () String)
(declare-fun N () String)
(declare-fun L () String)
(assert (= (str.++  G G F G "a" G G F G "b" L "b" N)  (str.++  "a" H F "a" H I J I J "baabaa") ))
(check-sat)
(get-model)
