(set-logic QF_S)
(declare-fun H () String)
(declare-fun G () String)
(declare-fun E () String)
(declare-fun F () String)
(assert (= (str.++  G F "a" G F "b" G)  (str.++  "a" E E H H "baa") ))
(check-sat)
(get-model)
