(set-logic QF_S)
(declare-fun I () String)
(declare-fun K () String)
(declare-fun R () String)
(declare-fun G () String)
(declare-fun L () String)
(declare-fun M () String)
(declare-fun P () String)
(assert (= (str.++  G "a" G "b" I I K I "b" L "ab" P)  (str.++  "a" I "aaaa" L K "a" L K "ab" M "a" M "ab" R R "baa") ))
(check-sat)
(get-model)
