(set-logic QF_S)
(declare-fun S () String)
(declare-fun J () String)
(declare-fun H () String)
(declare-fun K () String)
(declare-fun R () String)
(declare-fun G () String)
(declare-fun L () String)
(declare-fun M () String)
(declare-fun P () String)
(declare-fun Q () String)
(assert (= (str.++  G "aaa" G "aab" K K "b" P "a" P P "b" S "b" S)  (str.++  "a" H "aaa" L J "a" L J "ab" P "a" M P "a" M "b" Q R Q R "baabaa") ))
(check-sat)
(get-model)
