(set-logic QF_S)
(declare-fun I () String)
(declare-fun H () String)
(declare-fun F () String)
(declare-fun J () String)
(declare-fun N () String)
(declare-fun O () String)
(declare-fun L () String)
(assert (= (str.++  F F F F F F "aaa" F F F F F F "aabaa" I "b" L O "b" O)  (str.++  "a" H "a" F "aaaaa" J "aa" J "b" N L N L "baabaa") ))
(check-sat)
(get-model)
