(set-logic QF_S)
(declare-fun I () String)
(declare-fun K () String)
(declare-fun G () String)
(declare-fun E () String)
(assert (= (str.++  E E "aaa" E E "aab" I G "b" I)  (str.++  "a" G G I G I "b" K K "baa") ))
(check-sat)
(get-model)
