(set-logic QF_S)
(declare-fun J () String)
(declare-fun I () String)
(declare-fun K () String)
(declare-fun H () String)
(declare-fun G () String)
(declare-fun N () String)
(declare-fun M () String)
(declare-fun P () String)
(declare-fun Q () String)
(assert (= (str.++  G G G G G "aa" G G G G G "ab" K "a" K K K "a" K I "b" K K "ba" N "b" Q)  (str.++  "aa" H H H "a" H "aaa" G H "aa" H J J I K J J I K "b" M M M M "b" M M "b" P P "baa") ))
(check-sat)
(get-model)
