(set-logic ALL)
(declare-fun N () String)
(declare-fun J () String)
(declare-fun H () String)
(declare-fun R () String)
(declare-fun V () String)
(declare-fun G () String)
(declare-fun L () String)
(declare-fun M () String)
(declare-fun P () String)
(declare-fun Q () String)
(assert (= (str.++  J G G "aa" J G G "ab" L L "b" P P "b" V)  (str.++  "a" G "a" G "a" H "a" G H M M M M "b" Q N Q N "b" R R "baa") ))
(check-sat)
(get-model)
