(set-logic QF_S)
(declare-fun I () String)
(declare-fun G () String)
(declare-fun F () String)
(declare-fun E () String)
(declare-fun J () String)
(assert (= (str.++  F "a" F "aa" F "a" F "ab" G G "b" J)  (str.++  "aa" F E "aaaab" I I "baa") ))
(check-sat)
(get-model)
