(set-logic QF_S)
(declare-fun S () String)
(declare-fun J () String)
(declare-fun T () String)
(declare-fun H () String)
(declare-fun R () String)
(declare-fun I () String)
(declare-fun L () String)
(declare-fun N () String)
(declare-fun M () String)
(declare-fun P () String)
(assert (= (str.++  J "a" J "b" L L L L "b" N P "b" S)  (str.++  "a" H H "a" I N M M M N M M M "b" R R R R "b" T T "baa") ))
(check-sat)
(get-model)
