(set-logic QF_S)
(declare-fun G () String)
(declare-fun F () String)
(declare-fun E () String)
(declare-fun J () String)
(declare-fun D () String)
(assert (= (str.++  D "a" D "b" G)  (str.++  "a" E F J J "baa") ))
(check-sat)
(get-model)
