(set-logic QF_S)
(declare-fun H () String)
(declare-fun K () String)
(declare-fun I () String)
(declare-fun G () String)
(declare-fun J () String)
(assert (= (str.++  H H "aaaaaa" G "aa" H H "aaaaaa" G "ab" I H H "a" H H "a" H "b" I "a" I "aba" K "ba")  (str.++  "aaaaaaaaaa" G "aaaa" I H H I "a" I H I I H H I "a" I H I "b" J "aa" J "aab" J K J K "b" K K "baa") ))
(check-sat)
(get-model)
