(set-logic QF_S)
(declare-fun S () String)
(declare-fun N () String)
(declare-fun J () String)
(declare-fun I () String)
(declare-fun H () String)
(declare-fun V () String)
(declare-fun G () String)
(declare-fun L () String)
(declare-fun P () String)
(declare-fun Q () String)
(assert (= (str.++  J I "a" J I "b" L "ab" P P "b" S)  (str.++  "a" H G "a" N N "b" Q Q Q Q "b" V V "baa") ))
(check-sat)
(get-model)
