(set-logic QF_S)
(declare-fun J () String)
(declare-fun T () String)
(declare-fun R () String)
(declare-fun V () String)
(declare-fun G () String)
(declare-fun F () String)
(declare-fun L () String)
(declare-fun O () String)
(declare-fun M () String)
(assert (= (str.++  J "a" J "a" G "a" G "aa" J "a" J "a" G "a" G "ab" L J J "b" O R "b" V)  (str.++  "a" F F M M J M M M J M "ba" R "a" R "b" T T "baa") ))
(check-sat)
(get-model)
