(set-logic QF_S)
(declare-fun H () String)
(declare-fun K () String)
(declare-fun N () String)
(declare-fun E () String)
(declare-fun L () String)
(declare-fun O () String)
(declare-fun M () String)
(assert (= (str.++  E E "a" E E "b" K L "b" N)  (str.++  "a" H H M M M M "b" O O "baa") ))
(check-sat)
(get-model)
