(set-logic QF_S)
(declare-fun J () String)
(declare-fun I () String)
(declare-fun K () String)
(declare-fun H () String)
(declare-fun V () String)
(declare-fun F () String)
(declare-fun R () String)
(declare-fun L () String)
(declare-fun N () String)
(declare-fun O () String)
(assert (= (str.++  I I I "a" F "a" I I I "a" F "b" L J N K "b" N O "b" V)  (str.++  "a" H F F H "aa" N N K N N N K N "b" R N R N "b" R R "baa") ))
(check-sat)
(get-model)
