(set-logic QF_S)
(declare-fun H () String)
(declare-fun I () String)
(declare-fun N () String)
(declare-fun G () String)
(declare-fun L () String)
(assert (= (str.++  H "a" H "aa" H "a" H "ab" H H "b" L)  (str.++  "a" G I H I H "b" N N "baa") ))
(check-sat)
(get-model)
