(set-logic QF_S)
(declare-fun J () String)
(declare-fun H () String)
(declare-fun I () String)
(declare-fun L () String)
(declare-fun N () String)
(declare-fun M () String)
(declare-fun P () String)
(declare-fun Q () String)
(assert (= (str.++  H "aaaaaaaa" H "aa" H "a" H "aaaaaaaa" H "aa" H "baaaa" I "b" L "aa" L "b" N M "b" P)  (str.++  "a" H "aa" H H "aaaa" H "aa" J "aaaa" J "aaaab" L "a" L "a" L "a" L "ab" M N M N "b" Q Q "baa") ))
(check-sat)
(get-model)
