(set-logic QF_S)
(declare-fun S () String)
(declare-fun N () String)
(declare-fun J () String)
(declare-fun R () String)
(declare-fun K () String)
(declare-fun I () String)
(declare-fun U () String)
(declare-fun G () String)
(declare-fun F () String)
(declare-fun L () String)
(assert (= (str.++  G "a" G "b" K L "b" R R "b" S)  (str.++  "aaa" F J I L L "a" L L L "a" L "b" R N R N "b" U U "baa") ))
(check-sat)
(get-model)
