(set-logic QF_S)
(declare-fun H () String)
(declare-fun G () String)
(declare-fun F () String)
(declare-fun J () String)
(declare-fun L () String)
(declare-fun M () String)
(assert (= (str.++  "a" H H G H "aa" H H G H "b" H J "b" J J "b" L)  (str.++  "a" F H H H "aaa" J J J "a" J J J "ba" L "a" L "b" M M "baa") ))
(check-sat)
(get-model)
