(set-logic QF_S)
(declare-fun H () String)
(declare-fun K () String)
(declare-fun I () String)
(declare-fun G () String)
(declare-fun J () String)
(declare-fun N () String)
(declare-fun M () String)
(assert (= (str.++  H H H "a" G H H H "a" H H H "a" G H H H "baa" I "ab" K J "b" N)  (str.++  "a" G H G G H "a" G "a" H "a" I H "a" I "b" J K J K "b" M M "baa") ))
(check-sat)
(get-model)
