(set-logic QF_S)
(declare-fun I () String)
(declare-fun H () String)
(declare-fun G () String)
(declare-fun F () String)
(declare-fun J () String)
(assert (= (str.++  F G "aa" F G "ab" G H G "ab" I "b" I)  (str.++  "a" G G "aaaa" H H "a" H H H "a" H "b" H "a" H "ab" J J "baa") ))
(check-sat)
(get-model)
