(set-logic QF_S)
(declare-fun H () String)
(declare-fun F () String)
(declare-fun E () String)
(declare-fun L () String)
(declare-fun M () String)
(declare-fun Q () String)
(assert (= (str.++  E "a" E "b" L L "b" M)  (str.++  "a" F H M M M M "b" Q Q "baa") ))
(check-sat)
(get-model)
