(set-logic QF_S)
(declare-fun J () String)
(declare-fun H () String)
(declare-fun K () String)
(declare-fun I () String)
(declare-fun G () String)
(declare-fun L () String)
(declare-fun N () String)
(declare-fun O () String)
(declare-fun M () String)
(declare-fun P () String)
(assert (= (str.++  G H "a" I "aa" G H "a" I "ab" K K J "abaa" L "b" N "ba")  (str.++  "aaaa" H "aaa" H I "a" J "a" J K "aa" J "a" J K "ab" L "a" M L "a" M "b" O O "b" P P "baa") ))
(check-sat)
(get-model)
