(set-logic QF_S)
(declare-fun I () String)
(declare-fun H () String)
(declare-fun G () String)
(declare-fun F () String)
(declare-fun J () String)
(declare-fun N () String)
(declare-fun M () String)
(assert (= (str.++  "aa" G "aa" G "aaa" G "aa" G "baa" I "ab" J "ab" N)  (str.++  "a" F G G "a" H H "ba" J "a" J "b" M M "baa") ))
(check-sat)
(get-model)
