(set-logic QF_S)
(declare-fun S () String)
(declare-fun J () String)
(declare-fun R () String)
(declare-fun V () String)
(declare-fun F () String)
(declare-fun L () String)
(declare-fun M () String)
(declare-fun P () String)
(declare-fun Q () String)
(assert (= (str.++  J F "aa" J F "ab" L M "b" P P "b" V)  (str.++  "aa" F F "a" F F "aa" J L J L "b" R Q R Q "b" S S "baa") ))
(check-sat)
(get-model)
