(set-logic QF_S)
(declare-fun N () String)
(declare-fun J () String)
(declare-fun I () String)
(declare-fun K () String)
(declare-fun H () String)
(declare-fun G () String)
(declare-fun L () String)
(declare-fun O () String)
(declare-fun M () String)
(declare-fun Q () String)
(assert (= (str.++  G I "aaaaaaaa" G I "aaaaaaab" K "aa" K J J "b" M L L "ab" O O "b" Q)  (str.++  "a" H "aaaaaaaaa" J K "aa" K "aa" J K "aa" K "b" M M L "a" M M L "ab" N N "b" O O "baa") ))
(check-sat)
(get-model)
