(set-logic QF_S)
(declare-fun N () String)
(declare-fun I () String)
(declare-fun K () String)
(declare-fun H () String)
(declare-fun R () String)
(declare-fun G () String)
(declare-fun L () String)
(declare-fun O () String)
(assert (= (str.++  I I H I "a" I I H I "b" L K I "ba" L "b" O)  (str.++  "a" G H G H L "a" K K L "a" K K "b" N O N O "b" R R "baa") ))
(check-sat)
(get-model)
