(set-logic QF_S)
(declare-fun I () String)
(declare-fun K () String)
(declare-fun G () String)
(declare-fun E () String)
(declare-fun F () String)
(declare-fun M () String)
(declare-fun Q () String)
(assert (= (str.++  E G F "a" E G F "b" K I "b" M)  (str.++  "a" E F I I M I M "b" Q Q "baa") ))
(check-sat)
(get-model)
