(set-logic QF_S)
(declare-fun E () String)
(declare-fun J () String)
(declare-fun H () String)
(declare-fun K () String)
(declare-fun I () String)
(declare-fun F () String)
(declare-fun N () String)
(declare-fun Q () String)
(assert (= (str.++  E E "a" E E "b" K K "b" N)  (str.++  "a" F H I J I J "b" Q Q "baa") ))
(check-sat)
(get-model)
