(set-logic QF_S)
(declare-fun H () String)
(declare-fun G () String)
(declare-fun E () String)
(declare-fun F () String)
(declare-fun J () String)
(declare-fun N () String)
(declare-fun L () String)
(assert (= (str.++  F "a" G "a" F "a" G "ba" J "b" L)  (str.++  "a" E G G H J H J "b" N N "baa") ))
(check-sat)
(get-model)
