(set-logic QF_S)
(declare-fun H () String)
(declare-fun K () String)
(declare-fun G () String)
(declare-fun E () String)
(declare-fun L () String)
(declare-fun M () String)
(assert (= (str.++  H "aa" H "ab" K "ab" L)  (str.++  "a" E "a" G H H "b" M M "baa") ))
(check-sat)
(get-model)
