(set-logic QF_S)
(declare-fun J () String)
(declare-fun I () String)
(declare-fun K () String)
(declare-fun G () String)
(declare-fun L () String)
(declare-fun O () String)
(declare-fun M () String)
(declare-fun P () String)
(declare-fun Q () String)
(assert (= (str.++  I G "aaaaa" I G "aaaabaaaa" K K "aab" L M "ab" O O "b" P)  (str.++  "aaaaaaaaaaaaaaaaa" J "a" K "a" J "a" K "ab" M "a" M M M "a" M M "b" O M O M "b" Q Q "baa") ))
(check-sat)
(get-model)
