(set-logic QF_S)
(declare-fun J () String)
(declare-fun I () String)
(declare-fun K () String)
(declare-fun R () String)
(declare-fun V () String)
(declare-fun F () String)
(declare-fun H () String)
(declare-fun N () String)
(declare-fun M () String)
(assert (= (str.++  I F "aaa" I F "aab" K J "b" R N "b" V)  (str.++  "a" H H "aa" M N J M N J "b" R R R R "b" R R "baa") ))
(check-sat)
(get-model)
