(set-logic QF_S)
(declare-fun H () String)
(declare-fun K () String)
(declare-fun I () String)
(declare-fun G () String)
(declare-fun E () String)
(assert (= (str.++  "aa" E E "aaa" E E "b" H "ab" K)  (str.++  "aa" G G G "a" H "a" H "b" I I "baa") ))
(check-sat)
(get-model)
