(set-logic QF_S)
(declare-fun J () String)
(declare-fun H () String)
(declare-fun I () String)
(declare-fun K () String)
(declare-fun G () String)
(declare-fun L () String)
(declare-fun N () String)
(declare-fun M () String)
(declare-fun P () String)
(assert (= (str.++  H "a" H "a" H H G "aa" H H "a" H "a" H "a" H H G "aa" H H "b" I I "b" L "aaba" N "ba")  (str.++  "aa" H H H H "aa" H H H H H H "aaa" J J K J J J J K J J "b" M "a" M "ab" N N N N "b" P P "baa") ))
(check-sat)
(get-model)
