(set-logic QF_S)
(declare-fun L () String)
(declare-fun D () String)
(declare-fun E () String)
(declare-fun H () String)
(assert (= (str.++  D E "a" D E "b" L)  (str.++  "a" H H H "baa") ))
(check-sat)
(get-model)
