(set-logic QF_S)
(declare-fun H () String)
(declare-fun G () String)
(declare-fun E () String)
(declare-fun F () String)
(assert (= (str.++  F F "a" F "a" F F "a" F "b" F G "ba")  (str.++  "a" E "a" E "a" G G G G "b" H H "baa") ))
(check-sat)
(get-model)
