(set-logic QF_S)
(declare-fun S () String)
(declare-fun J () String)
(declare-fun V () String)
(declare-fun F () String)
(declare-fun L () String)
(declare-fun M () String)
(declare-fun P () String)
(declare-fun Q () String)
(assert (= (str.++  J "aaa" J J "aaa" J "aaa" J J "aab" J M "ba" P "b" V)  (str.++  "a" F F L M L M "b" Q P Q P "b" S S "baa") ))
(check-sat)
(get-model)
