(set-logic QF_S)
(declare-fun H () String)
(declare-fun K () String)
(declare-fun I () String)
(declare-fun G () String)
(declare-fun J () String)
(declare-fun M () String)
(assert (= (str.++  H "aa" H "ab" K J "b" K)  (str.++  "aaa" G "a" H I H I "b" M M "baa") ))
(check-sat)
(get-model)
