(set-logic QF_S)
(declare-fun H () String)
(declare-fun K () String)
(declare-fun I () String)
(declare-fun G () String)
(declare-fun J () String)
(declare-fun L () String)
(assert (= (str.++  G H "aaaa" G H "aaab" I H "ab" I J I I "b" J "ab" K)  (str.++  "aaaaaaa" G "aaaaaaa" I "aaaaa" I "aab" J J I J J J I J "b" K K K K "b" L L "baa") ))
(check-sat)
(get-model)
