(set-logic QF_S)
(declare-fun B () String)
(declare-fun D () String)
(declare-fun A () String)
(declare-fun C () String)
(assert (= (str.++  A "a" A "b" B "b" C "b" D)  (str.++  "a" A B B "b" C C "b" D D "baa") ))
(check-sat)
(get-model)
